// World AeroPress Championship podium recipes, as published (2008 onwards; no final in 2020).
// Researched from the official WAC and aeropress.com recipe pages plus coffee press write-ups.
// Values the sources disagree on are left empty and explained in `caveats`; millilitres are
// entered as grams (1 ml = 1 g). Text fields are shortened to fit the recipe form, and the full
// method is in `other_steps`. Recipe times follow the app's plan: for an inverted brew, "press
// starts at" is when the flip starts (the timer allows 10 s for it).
import type { RecipeFields } from './types';

/** A champion's setup in the app's recipe fields (no name, bean or notes: the team adds those). */
export type ChampionSetup = Omit<RecipeFields, 'name' | 'bean_id' | 'notes'>;

export interface ChampionRecipe {
  /** Stable, for links: wac-<year>-<place>. */
  id: string;
  year: number;
  place: 1 | 2 | 3;
  name: string;
  country: string;
  /** null when no recipe was ever published for this result. */
  recipe: ChampionSetup | null;
  /** The event, the coffee, and what's unusual about the recipe. */
  notes: string | null;
  /** What the sources leave open, and how the fields were filled from them. */
  caveats: string | null;
  sources: string[];
}

export const CHAMPION_RECIPES: ChampionRecipe[] = [
  {
    id: "wac-2025-1",
    year: 2025,
    place: 1,
    name: "Némo Pop",
    country: "Australia",
    recipe: {
      method: "Standard",
      filter: "Flow Control filter cap with 2 paper filters",
      dose_g: 18,
      water_g: 100,
      temp_c: 84,
      grinder: "Comandante Trailmaster X25 with Tigershark burrs",
      grind_setting: "31 clicks, sifted at 200 µm",
      water_recipe: "125 ppm water made with an APAX Lab prototype",
      bloom_water_g: 0,
      bloom_ends_s: 0,
      agitation: "At 0:25, stir north-south, north-south, west-east, west-east",
      press_starts_s: 50,
      press_duration_s: 20,
      bypass_g: 70,
      bypass_temp: "50 °C",
      other_steps: "Pour 70 g of 50 °C bypass water into the carafe first. Grind the coffee (slow rpm), blow away the chaff and sift out the fines through a 200 µm sieve. Stand the AeroPress upright (Flow Control cap, two paper filters) on the carafe and add the coffee. Pour 100 g of 84 °C water, wetting all the grounds. At 0:25, stir N-S, N-S, W-E, W-E. At 0:50, start pressing gently, for about 20 seconds, onto the bypass water.",
    },
    notes: "Held in Seoul in December 2025. Coffee: Ecuador Finca La Carolina (Fausto Romo), washed Sidra. No bloom: all 100 g go in with one pour.",
    caveats: "The 70 g bypass goes into the carafe before brewing and the coffee is pressed onto it, rather than being added after pressing. The press time is the recipe's 'about 20 seconds'.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/1st-nemo-pop-australia-2025",
      "https://worldaeropresschampionship.com/pages/recipes",
      "https://aeromatic.app/recipes/wac-2025-winner-flow-control-aeropress-recipe",
      "https://www.beanscenemag.com.au/australian-representative-wins-world-aeropress-championship/",
      "https://en.sedaily.com/news/2025/12/07/2025-world-aeropress-championship-concludes-successfully-in",
    ],
  },
  {
    id: "wac-2024-1",
    year: 2024,
    place: 1,
    name: "George Stanica",
    country: "Romania",
    recipe: {
      method: "Inverted",
      filter: "1 Aesir paper filter, rinsed",
      dose_g: 18,
      water_g: 100,
      temp_c: 96,
      grinder: "Comandante C40 Mk4 (Red Clix)",
      grind_setting: "58 clicks (870 µm)",
      water_recipe: "Aquacode diluted to about 85-90 ppm with 0 ppm water",
      bloom_water_g: 50,
      bloom_ends_s: null,
      agitation: "Light north-south-east-west stir for 10 seconds after the second pour; a gentle swirl after capping",
      press_starts_s: null,
      press_duration_s: null,
      bypass_g: null,
      bypass_temp: "Warm, then room temp",
      other_steps: "Set the AeroPress up inverted, with the plunger around the 4 mark, and add 18 g of coffee. Pour about 50 g of water with a Melodrip (5-6 seconds) and let it bloom for about 30 seconds. Pour another 50 g (5-6 seconds). Stir lightly north-south-east-west for 10 seconds. Wait until 1:20, then put on the cap with the filter and gently remove the air (about 10 seconds). Swirl gently and place the AeroPress on the server. At 1:35, start pressing gently until you have the full output (about 76-79 g), over 30-40 seconds. Add warm water from the kettle up to 130-135 g, then another 20-30 g of room-temperature 0 ppm water.",
    },
    notes: "Held in Lisbon in September 2024. Stanica is a home brewer who works in IT. Barista Magazine calls him George Popescu; the WAC, aeropress.com and BeanScene all use George Stanica. Coffee: washed Ethiopia Guji (Arsosala washing station), sourced by Cafe Imports, roasted by Olisipo. A widely shared home adaptation (240-255 g of ordinary filtered water at 93 °C) is not the competition recipe.",
    caveats: "The water and the bloom water come from two pours of 'approximately 50 g'. The bloom end is left empty: the bloom is 'about 30 seconds' after a 5-6 s pour, with no timestamp. The press start is left empty: 1:35 is when pressing starts, and the flip comes a few seconds earlier (after capping at 1:20 and about 10 s of air removal); the app adds 10 s for the flip, so a press start of 1:25 would put the pressing at 1:35. The press time is left empty: the recipe gives 30-40 s. The bypass is left empty: the top-ups are to target weights (130-135 g, then 20-30 g more).",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/1st-george-stanica-romania-2024",
      "https://worldaeropresschampionship.com/pages/1st-george-stanica-romania-2024",
      "https://www.beanscenemag.com.au/world-aeropress-champion-2024-crowned-in-portugal/",
      "https://www.baristamagazine.com/george-popescu-the-software-engineer-who-brewed-his-way-to-aeropress-victory/",
    ],
  },
  {
    id: "wac-2024-2",
    year: 2024,
    place: 2,
    name: "Sophan Nugraha",
    country: "Indonesia",
    recipe: {
      method: "Inverted",
      filter: "2 Cafec paper filters, trimmed to fit, rinsed",
      dose_g: 18,
      water_g: 190,
      temp_c: null,
      grinder: "Comandante C40 (Nitro Blade burrs)",
      grind_setting: "22 clicks",
      water_recipe: "Caldas de Penacova mineral water",
      bloom_water_g: 60,
      bloom_ends_s: 40,
      agitation: "Stir 8 times after the bloom pour",
      press_starts_s: 90,
      press_duration_s: 30,
      bypass_g: 10,
      bypass_temp: "Room temperature",
      other_steps: "Inverted. Put 18 g of coffee in the chamber and pour 60 ml of room-temperature water to bloom. Stir 8 times and wait until 0:40. Pour 95 °C water up to 190 ml. At 1:30, flip and press until 2:00. Dilute with 10 ml of room-temperature water.",
    },
    notes: "The bloom uses room-temperature water and the main pour 95 °C water. Competition coffee as for the 2024 winner (Ethiopia Guji, Arsosala, roasted by Olisipo). aeropress.com's page for him gives a different, Flow Control filter cap version (180 ml at 80 °C plus 20 ml at room temperature, Sanford water); this entry follows the competition recipe on the WAC page.",
    caveats: "The temperature is left empty because two temperatures are used (room-temperature bloom, 95 °C main pour). The recipe gives water in millilitres; the water, the bloom water and the bypass use 1 ml = 1 g. The press time (0:30) runs from the flip at 1:30 to 2:00, so it includes the flip. Only the WAC page has the competition version (see notes).",
    sources: [
      "https://worldaeropresschampionship.com/pages/2nd-sophan-nugraha-indonesia-2024",
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/2nd-sophan-nugraha-indonesia-2024",
    ],
  },
  {
    id: "wac-2023-1",
    year: 2023,
    place: 1,
    name: "Tay Wipvasutt",
    country: "Thailand",
    recipe: {
      method: "Inverted",
      filter: "1 paper filter, rinsed",
      dose_g: 18,
      water_g: 100,
      temp_c: 89,
      grinder: "1Zpresso ZP6",
      grind_setting: "65 clicks",
      water_recipe: "Perfect Coffee Water at 81.5% strength",
      bloom_water_g: 0,
      bloom_ends_s: 0,
      agitation: "Stir for 5 seconds at 0:30 with one end of a chopstick; stir for another 5 seconds at 0:55",
      press_starts_s: null,
      press_duration_s: 30,
      bypass_g: null,
      bypass_temp: "Room temp, then hot",
      other_steps: "Inverted. Put 16 g of coffee in the AeroPress and pour hot (89 °C) water to 100 g. At 0:30, stir for 5 seconds with one end of a chopstick. At 0:45, add the other 2 g of coffee. At 0:55, stir for another 5 seconds. Press the AeroPress down so the plunger rises and removes the excess air; close the cap. Flip carefully and press down at 1:35, for about 30 seconds. The yield should be about 75 g. Bypass with room-temperature water to 115 g, then with hot water to about 155 g.",
    },
    notes: "Held at Fieldwork Coffee, Melbourne, on 2 December 2023. Also written 'Ekameth (Tay) Wipvasutti' (Brave Roasters). Coffee: washed Kenya AB, Karindundu (Nyeri), sourced by Cafe Imports, roasted by Fieldwork Coffee. The dose is the total: 16 g at the start plus 2 g added at 0:45. No bloom: all the water goes in with one pour.",
    caveats: "The press start is left empty: the recipe says 'flip carefully and press down at 1:35', so it isn't clear whether 1:35 is the flip or the start of pressing (the app adds 10 s for the flip). The press time is the recipe's 'about 30 seconds'. The bypass is left empty: the bypass is to target weights (115 g, then about 155 g), so the amount depends on the roughly 75 g yield.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/1st-tay-wipvasutt-thailand-2023",
      "https://worldaeropresschampionship.com/pages/1st-tay-wipvasutt-thailand-2023",
      "https://www.beanscenemag.com.au/ekameth-wipvasutti-wins-2023-world-aeropress-championship/",
    ],
  },
  {
    id: "wac-2022-1",
    year: 2022,
    place: 1,
    name: "Jibbi Little",
    country: "Australia",
    recipe: {
      method: "Inverted",
      filter: "1 AeroPress paper filter, rinsed",
      dose_g: 18,
      water_g: 94,
      temp_c: 92,
      grinder: "Timemore, then Kinu M47",
      grind_setting: "Kinu at 4, fines sifted out",
      water_recipe: "Perfect Coffee Water (mineral packet added to distilled water)",
      bloom_water_g: 0,
      bloom_ends_s: 0,
      agitation: "Stir gently 35 times after the pour",
      press_starts_s: 90,
      press_duration_s: 30,
      bypass_g: null,
      bypass_temp: "90 °C",
      other_steps: "Grind 18 g on a Timemore at a very coarse setting and blow off the silver skin, then regrind on a Kinu at setting 4 and sift out the fines (100-200 µm). Inverted, with one rinsed AeroPress paper filter. Put the coffee in the chamber, pour 94 ml of 92 °C water and stir gently 35 times. At 1:20: screw on the cap and press out the remaining air. At 1:30: flip. Press for 30 seconds, 1:40-2:10. Optionally press onto chilled 'ice' balls (3 in the bottom of the server, 1 on top) to cool the brew. You get about 58-64 g of concentrate; bypass with 90 °C water up to 150 g. Target TDS 1.30-1.35%.",
    },
    notes: "Held in Vancouver, 1-3 December 2022. Coffee: Colombia Finca Juan Martin, natural Striped Red Bourbon (Quietly Coffee x Cafe Imports). No bloom: all the water goes in with one pour.",
    caveats: "The water: every source gives '94 ml'; entered as 94 g (1 ml = 1 g). The bypass is left empty: she tops up to a final weight of 150 g, so the amount depends on the yield (about 58-64 g).",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/1st-jibbi-little-australia-2022",
      "https://worldaeropresschampionship.com/pages/1st-jibbi-little-australia-2022",
      "https://europeancoffeetrip.com/wac-2022-winning-recipe/",
      "https://www.beanscenemag.com.au/winner-of-2022-world-aeropress-championship-announced/",
    ],
  },
  {
    id: "wac-2022-2",
    year: 2022,
    place: 2,
    name: "Simon Derutter",
    country: "Belgium",
    recipe: {
      method: "Standard",
      filter: "Aesir paper filter",
      dose_g: 18,
      water_g: 140,
      temp_c: 90,
      grinder: "Comandante",
      grind_setting: "23 clicks (medium)",
      water_recipe: "Perfect Coffee Water",
      bloom_water_g: 0,
      bloom_ends_s: 0,
      agitation: null,
      press_starts_s: 75,
      press_duration_s: 30,
      bypass_g: 46,
      bypass_temp: null,
      other_steps: "Add 18 g of coffee to the chamber, then 140 g of 90 °C water all at once. Insert the plunger into the top of the chamber to halt the brewing. Wait 1 minute 15 seconds. Press for 30 seconds. Add around 46 g of water. Total time 1:45.",
    },
    notes: "A very simple recipe. The listed 186 g of water includes the roughly 46 g added after pressing. Competition coffee as for the 2022 winner (Colombia Finca Juan Martin). No bloom: all 140 g go in at once.",
    caveats: "The press start is the recipe’s 1:15 wait, which with the 30 s press matches the listed 1:45 total. The bypass is the recipe's 'around 46 g'; its temperature isn't given. No stirring is mentioned.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/2nd-simon-derutter-belgium-2022",
      "https://worldaeropresschampionship.com/pages/2nd-simon-derutter-belgium-2022",
      "https://aeromatic.app/recipes/wac-2022-runner-up-aeropress-recipe",
    ],
  },
  {
    id: "wac-2022-3",
    year: 2022,
    place: 3,
    name: "Jennifer Rui Ping Ho",
    country: "Singapore",
    recipe: {
      method: "Inverted",
      filter: "1 AeroPress paper filter, dry (not rinsed)",
      dose_g: 18,
      water_g: 200,
      temp_c: 84,
      grinder: "Comandante",
      grind_setting: "30 clicks (coarse)",
      water_recipe: "Perfect Coffee Water",
      bloom_water_g: 100,
      bloom_ends_s: 30,
      agitation: "Stir gently after each 100 ml pour",
      press_starts_s: 90,
      press_duration_s: 30,
      bypass_g: 0,
      bypass_temp: null,
      other_steps: "Inverted. Put the coffee in the chamber. Pour 100 ml of 84 °C water and stir gently. Bloom for 30 seconds, then add another 100 ml and stir gently. At 1:30, flip and press for 30 seconds. Finish at 2:00. Aerate and serve.",
    },
    notes: "Competition coffee as for the 2022 winner (Colombia Finca Juan Martin). The WAC page address spells her name 'Jessica'; the page itself says Jennifer. No dilution: the recipe ends with 'aerate and serve'.",
    caveats: "The recipe gives water in millilitres (2 x 100 ml); the water and the bloom water use 1 ml = 1 g.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/3rd-jennifer-rui-ping-ho-singapore-2022",
      "https://worldaeropresschampionship.com/pages/3rd-jessica-rui-ping-ho-singapore-2022",
      "https://www.tiktok.com/@cafefabrique/video/7236809178868747525",
    ],
  },
  {
    id: "wac-2021-1",
    year: 2021,
    place: 1,
    name: "Tuomas Merikanto",
    country: "Finland",
    recipe: {
      method: "Inverted",
      filter: "2 paper filters, rinsed",
      dose_g: 18,
      water_g: 200,
      temp_c: 80,
      grinder: "Macap Labo 70D",
      grind_setting: "7.0",
      water_recipe: "Third Wave Water, Formula 2 (100% Espresso profile)",
      bloom_water_g: 50,
      bloom_ends_s: 15,
      agitation: "Stir very gently back and forth 3 times at 0:10-0:15; stir very gently 3 more times at 0:50",
      press_starts_s: 100,
      press_duration_s: 20,
      bypass_g: 0,
      bypass_temp: null,
      other_steps: "Insert the plunger to the middle of the '4' and invert. 0:00-0:10: add 50 g of water at 80 °C. 0:10-0:15: stir very gently back and forth 3 times. 0:15-0:30: pour up to 200 g. 0:30-0:50: let it brew; at 0:50 stir very gently 3 more times. At 1:00: push the excess air out; put two paper filters in the cap, rinse them, attach the cap and let it brew until 1:40. At 1:35: put the pitcher on. At 1:40: flip, and press straight away, 1:40-2:00. Swirl from 2:00 to 2:30, then pour from a height into another pitcher.",
    },
    notes: "The 2021 final was virtual: national champions sent in recipes that surrogate baristas brewed at Bureaux Coffee in Melbourne, and the result was announced in March 2022. Every competitor built their water from distilled water plus Third Wave Water minerals; he was the only one to use the 100% espresso profile. No dilution: the recipe ends with the swirl and the pour into another pitcher.",
    caveats: null,
    sources: [
      "https://worldaeropresschampionship.com/pages/2022-1st-place-tuomas-merikanto-finland",
      "https://europeancoffeetrip.com/winning-aeropress-recipe-2021/",
      "https://dailycoffeenews.com/2022/03/14/here-are-the-winners-of-the-2021-world-aeropress-championship/",
      "https://www.beanscenemag.com.au/how-finlands-tuomas-merikanto-won-the-first-and-hopefully-last-virtual-world-aeropress-championship/",
    ],
  },
  {
    id: "wac-2021-2",
    year: 2021,
    place: 2,
    name: "Maru Mallee",
    country: "Netherlands",
    recipe: {
      method: "Inverted",
      filter: "1 paper filter, rinsed",
      dose_g: 18,
      water_g: 150,
      temp_c: 93,
      grinder: "Macap Labo 70D",
      grind_setting: "6.7",
      water_recipe: "Third Wave Water Formula 6 (75% Classic, 25% distilled)",
      bloom_water_g: 0,
      bloom_ends_s: 0,
      agitation: "Stir firmly 20 times at 0:12-0:25; after flipping, swirl 3 times and tap down twice",
      press_starts_s: 110,
      press_duration_s: 20,
      bypass_g: 36,
      bypass_temp: "Room temperature",
      other_steps: "Insert the plunger to the middle of the '4' and stand the AeroPress upside down. Add 18 g of coffee. 0:00-0:12: pour 150 g of 93 °C water. 0:12-0:25: stir firmly 20 times. 0:25-0:30: screw on the filter cap, press out the extra air and put the carafe on top. At 1:50: flip the carafe and AeroPress together, swirl three times and tap down twice. 1:55-2:15: press with light pressure, don't force it. At 2:15 remove the brewer, shaking it gently so the last coffee drips into the carafe. Dilute with 36 g of room-temperature Formula 6 water. Swirl for 1 minute to cool, then serve.",
    },
    notes: "The 2021 final was virtual; surrogate baristas brewed the recipes in Melbourne. The listed 186 g of water includes the 36 g dilution. No bloom: all 150 g go in with one pour.",
    caveats: null,
    sources: [
      "https://worldaeropresschampionship.com/pages/2021-2nd-maru-mallee-the-netherlands",
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/2nd-maru-mallee-the-netherlands-2021",
      "https://aeroprecipe.com/recipes/2021-world-aeropress-championship-2nd-place",
    ],
  },
  {
    id: "wac-2021-3",
    year: 2021,
    place: 3,
    name: "Brandon Smith",
    country: "South Africa",
    recipe: {
      method: "Inverted",
      filter: "1 AeroPress paper filter, rinsed",
      dose_g: 18,
      water_g: 140,
      temp_c: 88,
      grinder: "Macap Labo 70D",
      grind_setting: "3.3",
      water_recipe: "Third Wave Water Formula 4 (50% Classic, 50% Espresso)",
      bloom_water_g: 0,
      bloom_ends_s: 0,
      agitation: "Stir gently back to front 5 times after the pour; one gentle swirl after flipping",
      press_starts_s: 85,
      press_duration_s: 30,
      bypass_g: 80,
      bypass_temp: "Kettle water (temp not given)",
      other_steps: "Insert the plunger to the middle of the '4' and stand the AeroPress upside down. Add 18 g of coffee. Start the timer and pour 140 g of 88 °C water within 10 seconds. Stir gently back to front 5 times, then let it brew. Put one AeroPress paper filter in the cap, rinse it with a little water and screw the cap on. Carefully press out the air. At 1:25, flip and give one gentle swirl. Press from 1:30 to 2:00, through the hiss. Dilute with 80 g of water from the open kettle. Swirl and let it stand for 1 minute before serving.",
    },
    notes: "His first coffee competition. The 2021 final was virtual; surrogate baristas brewed the recipes in Melbourne. The listed 220 g of water includes the 80 g dilution. No bloom: all 140 g go in with one pour.",
    caveats: "The dilution water's temperature isn't given ('from open kettle').",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/3rd-brandon-smith-south-africa-2021",
      "https://magazine.coffee/blog/1/6343/interview-recipe-brandon-smith-on-his-3rd-place-in-world-aeropress-champs-2021",
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/brandon-smith",
    ],
  },
  {
    id: "wac-2019-1",
    year: 2019,
    place: 1,
    name: "Wendelien van Bunnik",
    country: "Netherlands",
    recipe: {
      method: "Inverted",
      filter: "Aesir paper filter, rinsed",
      dose_g: 30,
      water_g: 100,
      temp_c: 92,
      grinder: "Mahlkönig EK43S",
      grind_setting: "7/10 (card scale, 10 = very coarse)",
      water_recipe: "Spa Blauw (30 ppm)",
      bloom_water_g: 0,
      bloom_ends_s: 0,
      agitation: "Stir firmly 20 times in 10 seconds, right after the pour",
      press_starts_s: 40,
      press_duration_s: null,
      bypass_g: 120,
      bypass_temp: null,
      other_steps: "Inverted. Pour 100 g of 92 °C water onto 30 g of coffee in 10 seconds. Stir firmly 20 times in 10 seconds. Put on the cap with a rinsed Aesir filter and gently press out the excess air. At 0:40, flip and press out all the coffee; you should get roughly 60 g of concentrate. Taste and add water until it's as strong as you like (she used 120 g). Cool the brew to about 60 °C by stirring and decanting.",
    },
    notes: "Coffee: Pacas from Orlando Aguilar (El Salvador), roasted by Ozone Coffee Roasters (London). No bloom: all 100 g go in with one pour. The grind is on the WAC recipe card’s 1–10 scale (1 = very fine, 10 = very coarse).",
    caveats: "The press time is left empty: not published. The bypass is the 120 g she used; the recipe says to dilute to taste. The dilution water's temperature isn't given. The grinder (EK43S) comes from the European Coffee Trip and AeroPrecipe write-ups.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/1st-wendelien-van-bunnik-the-netherlands-2019",
      "https://europeancoffeetrip.com/winning-aeropress-recipe-2019/",
      "https://aeroprecipe.com/recipes/2019-wac-1st-place",
    ],
  },
  {
    id: "wac-2019-2",
    year: 2019,
    place: 2,
    name: "Benja Khemacheva",
    country: "Thailand",
    recipe: {
      method: "Inverted",
      filter: "1 paper filter plus 1 metal filter, rinsed",
      dose_g: 35,
      water_g: 100,
      temp_c: 94,
      grinder: null,
      grind_setting: "8/10 (card scale, 10 = very coarse)",
      water_recipe: "80 ppm",
      bloom_water_g: 0,
      bloom_ends_s: 0,
      agitation: "Stir for 15 seconds, then a turbulent wiggle for 10 seconds",
      press_starts_s: 75,
      press_duration_s: 30,
      bypass_g: 110,
      bypass_temp: "94 °C",
      other_steps: "Put 110 g of 94 °C water in the server first. Put 1 paper and 1 metal filter in the filter cap and rinse. Inverted: add 35 g of ground coffee to the chamber, then 100 g of water. Stir for 15 seconds, then give it a turbulent wiggle for 10 seconds. Wait until 1:15, put on the filter cap and flip. Press into the server (onto the 110 g of water) for 30 seconds, using your elbow. Total brew time 1:45.",
    },
    notes: "The bypass water sits in the server before brewing, so the concentrate is pressed onto it. Competition coffee as for the 2019 winner (Pacas, Ozone Coffee Roasters). No bloom: all 100 g go in with one pour. The grind is on the WAC recipe card’s 1–10 scale (1 = very fine, 10 = very coarse).",
    caveats: "The press time (0:30) runs from the flip at 1:15 to the 1:45 finish, so it includes the flip. Grinder not published.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/2nd-benja-khemacheva-thailand-2019",
      "https://worldaeropresschampionship.com/pages/2nd-benja-khemacheva-thailand-2019",
      "https://aeroprecipe.com/recipes/2019-wac-2nd-place",
    ],
  },
  {
    id: "wac-2018-1",
    year: 2018,
    place: 1,
    name: "Carolina Ibarra Garay",
    country: "USA",
    recipe: {
      method: "Inverted",
      filter: "Paper, rinsed with hot water",
      dose_g: 34.9,
      water_g: 100,
      temp_c: 85,
      grinder: "Mahlkönig EK43S",
      grind_setting: "8/10 (card scale, 10 = very coarse)",
      water_recipe: "Brita-filtered water",
      bloom_water_g: 0,
      bloom_ends_s: 0,
      agitation: "Stir vigorously but carefully with wooden chopsticks for 30 seconds, right after the pour",
      press_starts_s: 60,
      press_duration_s: 30,
      bypass_g: 100,
      bypass_temp: "85 °C (60 g) and room temp (40 g)",
      other_steps: "Set the water to 85 °C. Rinse the paper filter with hot water and grind the coffee. Inverted: pour 100 g of water over 30 seconds. Stir vigorously but carefully with wooden chopsticks for 30 seconds. Put the filter cap on, flip, and press into a glass server over 30 seconds. Don't preheat the serving vessel. Top up with 60 g of 85 °C water and 40 g of room-temperature water.",
    },
    notes: "Held in Sydney; the first world champion from the USA. Coffee: Mugaya AA (Kirinyaga, Kenya), roasted by Single O, sourced by Cafe Imports. The published 'water weight' of 200 g includes the 100 g top-up. No bloom: all 100 g go in with one pour. The grind is on the WAC recipe card’s 1–10 scale (1 = very fine, 10 = very coarse).",
    caveats: "The press start (1:00) is worked out from the stated steps (30 s pour, then 30 s stir, then cap on and flip); no source gives it as a timestamp.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/1st-carolina-ibarra-garay-usa-2018",
      "https://worldaeropresschampionship.com/pages/1st-carolina-garay-usa-2018",
      "https://dailycoffeenews.com/2018/11/20/carolina-ibarra-garays-winning-recipe-from-the-world-aeropress-championship/",
      "https://www.baristamagazine.com/recipes-2018-wac/",
    ],
  },
  {
    id: "wac-2018-2",
    year: 2018,
    place: 2,
    name: "Xiaobo Zhang",
    country: "China",
    recipe: {
      method: "Inverted",
      filter: "Kalita paper filter (95 mm), rinsed with cold water",
      dose_g: 31,
      water_g: 170,
      temp_c: 80,
      grinder: null,
      grind_setting: "10/10 (card scale) + 1 g very fine",
      water_recipe: null,
      bloom_water_g: 100,
      bloom_ends_s: 30,
      agitation: "Stir for 15 seconds after the first 100 g",
      press_starts_s: null,
      press_duration_s: 45,
      bypass_g: 50,
      bypass_temp: null,
      other_steps: "Inverted. Add 30 g of coffee to the chamber. Add 100 g of 80 °C water over 15 seconds and stir for 15 seconds. Add 70 g of water. Add 1 g of very finely ground coffee (like espresso). Attach the filter cap, flip and press for 45 seconds. Top up the brew with 50 g of water. Total brew time 1:15.",
    },
    notes: "Adds 1 g of espresso-fine coffee partway through the brew. The dose is the total (30 g + 1 g). The listed 220 g of water includes the 50 g top-up. The grind is on the WAC recipe card’s 1–10 scale (1 = very fine, 10 = very coarse).",
    caveats: "The bloom water and the bloom end describe the first of two pours (100 g over 15 s plus 15 s of stirring), worked out from the stated step times. The press start is left empty: the 70 g pour, the 1 g addition and the flip have no stated times. The top-up water's temperature and the grinder aren't given.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/2nd-xiaobo-zhang-china-2018",
      "https://worldaeropresschampionship.com/pages/2nd-xiaobo-zhang-china-2018",
      "https://www.baristamagazine.com/recipes-2018-wac/",
    ],
  },
  {
    id: "wac-2018-3",
    year: 2018,
    place: 3,
    name: "Evgeni Pinchukov",
    country: "Belarus",
    recipe: {
      method: "Standard",
      filter: "2 paper filters, rinsed with hot water",
      dose_g: 15,
      water_g: 230,
      temp_c: 80,
      grinder: "Comandante",
      grind_setting: null,
      water_recipe: null,
      bloom_water_g: 50,
      bloom_ends_s: null,
      agitation: "Stir after the bloom pour; stir again at 1:05",
      press_starts_s: 65,
      press_duration_s: null,
      bypass_g: null,
      bypass_temp: null,
      other_steps: "Upright AeroPress with two paper filters rinsed with hot water. Start the timer. Add the coffee and 50 g of 80 °C water and let it bloom. Stir, then wait 30 seconds. Add 180 g of water. Wait until the timer reads 1:05, then stir. Put the plunger back on top of the chamber and start pressing. Stop when the coffee grounds are just visible above the water line.",
    },
    notes: "A small 15 g dose, and the press stops before the bed is dry.",
    caveats: "The grind setting is left empty: the recipe card gives 8/10 on its 1-10 scale (10 = very coarse), but Barista Magazine describes the grind as fine. The bloom end is left empty: the 30 s wait comes after an untimed pour and stir. The press start is the recipe’s 1:05 mark, followed by a stir and the plunger going on. The press runs until the grounds show, not for a set time. No dilution is mentioned.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/3rd-evgeni-pinchukov-belarus-2018",
      "https://worldaeropresschampionship.com/pages/3rd-evgeni-pinchukov-belarus-2018",
      "https://www.baristamagazine.com/recipes-2018-wac/",
    ],
  },
  {
    id: "wac-2017-1",
    year: 2017,
    place: 1,
    name: "Paulina Miczka",
    country: "England",
    recipe: {
      method: "Inverted",
      filter: "Paper, pre-wetted",
      dose_g: 35,
      water_g: 150,
      temp_c: 84,
      grinder: null,
      grind_setting: "Coarse (8/10)",
      water_recipe: "Aqua Pura with some Third Wave Water minerals added",
      bloom_water_g: 0,
      bloom_ends_s: 0,
      agitation: "Stir continuously from 0:15 to 0:35 (European Coffee Trip: 35 stirs)",
      press_starts_s: 65,
      press_duration_s: 30,
      bypass_g: null,
      bypass_temp: "Hot water",
      other_steps: "Inverted, 35 g of coarse coffee. 0:00-0:15: add 150 g of 84 °C water. 0:15-0:35: stir and keep stirring. At 0:35: put on the cap with a pre-wet paper filter. At 1:05: flip and start pressing. At 1:35: stop pressing; you should have about 90 ml of concentrate (about 4.5% TDS). Add 160-200 g of hot water.",
    },
    notes: "Held in Seoul; she got in through the wildcard round. She started in coffee in Poland and worked at Kaffeine in London; the official listing gives her country as England. Coffee: Kenya Kamwangi AA roasted by Fritz Coffee Company (Seoul). The press time runs from the flip at 1:05 to the end of pressing at 1:35, so it includes the flip. No bloom: all 150 g go in with one pour.",
    caveats: "The bypass is left empty: the official listing says 160-200 g of hot water, European Coffee Trip says 170 ml. The total water differs between sources (320 ml, 330 g, 370 g); the 150 g brew water is consistent. The water recipe comes from European Coffee Trip only. Grinder not published.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/1st-paulina-miczka-england-2017",
      "https://worldaeropresschampionship.com/pages/1st-paulina-miczka-england-2017",
      "https://europeancoffeetrip.com/paulina-miczka-world-aeropress-champion-2017/",
      "https://www.baristamagazine.com/winning-recipes-2017-world-aeropress-competition/",
    ],
  },
  {
    id: "wac-2017-2",
    year: 2017,
    place: 2,
    name: "Yusuke Narisawa",
    country: "Japan",
    recipe: {
      method: "Inverted",
      filter: "2 paper filters, wetted",
      dose_g: 29.5,
      water_g: 170,
      temp_c: 85,
      grinder: null,
      grind_setting: "9/10 (card scale) + 1.5 g very fine",
      water_recipe: null,
      bloom_water_g: 70,
      bloom_ends_s: null,
      agitation: "Stir 20 times after the first 70 g",
      press_starts_s: null,
      press_duration_s: null,
      bypass_g: 75,
      bypass_temp: "Hot water",
      other_steps: "Inverted. Add the coffee: 28 g coarsely ground plus 1.5 g of very finely ground powder. Start the timer as you pour: add 70 g of 85 °C water and stir 20 times. Add 100 g of water. Put on the cap with a wet double paper filter and flip. Press slowly, finishing at 1:50. Add 75 g of hot water.",
    },
    notes: "Two grind sizes in one dose. The dose is the total (28 g + 1.5 g). The listed 245 g of water includes the 75 g added after pressing. The grind is on the WAC recipe card’s 1–10 scale (1 = very fine, 10 = very coarse).",
    caveats: "Only the end of pressing (1:50) is timed, so the bloom end, the press start and the press time are left empty. The bloom water is the first of two pours (70 g, then 100 g). Grinder not published.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/2nd-yusuke-narisawa-japan-2017",
      "https://worldaeropresschampionship.com/pages/2nd-yusuke-narisawa-japan-2017",
      "https://www.baristamagazine.com/winning-recipes-2017-world-aeropress-competition/",
      "https://aeroprecipe.com/recipes/2017-wac-2nd-place",
    ],
  },
  {
    id: "wac-2017-3",
    year: 2017,
    place: 3,
    name: "Jeongsu Park",
    country: "South Korea",
    recipe: {
      method: "Standard",
      filter: "Metal filter plus a paper filter",
      dose_g: 30,
      water_g: 150,
      temp_c: 86,
      grinder: null,
      grind_setting: "3/10 (card scale, 10 = very coarse)",
      water_recipe: null,
      bloom_water_g: 75,
      bloom_ends_s: null,
      agitation: "Stir 6 times after the first 75 g; stir 5 times after the second 75 g",
      press_starts_s: null,
      press_duration_s: 10,
      bypass_g: 150,
      bypass_temp: "86 °C",
      other_steps: "Put the metal filter, then the paper filter, in the filter cap. Fit the cap on the brewer (upright) and add the coffee. Add 75 g of 86 °C water and stir six times. Wait 45 seconds. Add 75 g of 86 °C water and stir five times. Put the plunger in place and wait one minute. Press down for 10 seconds. Add 150 g of 86 °C water to the brewed coffee.",
    },
    notes: "Metal plus paper filter, and a short 10-second press. The grind is on the WAC recipe card’s 1–10 scale (1 = very fine, 10 = very coarse).",
    caveats: "The listing's total water (230 g) doesn't match its steps (75 + 75 + 150 = 300 g); the water and the bypass use the step amounts. The waits are relative (45 s, then 1 minute) with untimed pours and stirs between them, so the bloom end and the press start are left empty. Grinder not published.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/3rd-jeongsu-park-south-korea-2017",
      "https://worldaeropresschampionship.com/pages/3rd-jeongsu-park-south-korea-2017",
      "https://dailycoffeenews.com/2017/12/01/press-with-the-best-recipes-from-the-2017-world-aeropress-championship-in-seoul/",
    ],
  },
  {
    id: "wac-2016-1",
    year: 2016,
    place: 1,
    name: "Filip Kucharczyk",
    country: "Poland",
    recipe: {
      method: "Inverted",
      filter: "Paper, rinsed",
      dose_g: 35,
      water_g: 150,
      temp_c: null,
      grinder: null,
      grind_setting: "Coarse",
      water_recipe: null,
      bloom_water_g: 0,
      bloom_ends_s: 0,
      agitation: "Stir from the end of the pour until 0:35 on the timer (0:30 on the official listing); swirl after flipping",
      press_starts_s: 60,
      press_duration_s: null,
      bypass_g: null,
      bypass_temp: null,
      other_steps: "Inverted, rinsed paper filter, 35 g of coarsely ground coffee. Start the timer and pour 150 g of water over 15 seconds. Stir until 0:35 on the timer (the official listing says 0:30). Put the cap on and wait until 1:00. Flip the AeroPress, give it a swirl, and press. Add 100-120 g of water to taste.",
    },
    notes: "Held in Dublin. A large dose, a coarse grind and a low temperature for a gentle extraction, then diluted. No bloom: all 150 g go in with one pour.",
    caveats: "The temperature is left empty because the sources disagree: 81 °C on the official WAC / aeropress.com listing, 84 °C in European Coffee Trip, Sprudge and Barista Magazine, 85 °C on AeroPrecipe. The end of stirring is 0:30 (official) or 0:35 (the others). The bypass is left empty: the recipe gives a range (100-120 g, to taste) and no temperature. The press time is left empty: only AeroPrecipe's version gives an end time (around 1:30).",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/1st-filip-kucharczyk-poland-2016",
      "https://europeancoffeetrip.com/winning-aeropress-recipe-2016-filip-kucharczyk/",
      "https://sprudge.com/the-world-aeropress-championship-recipe-and-a-very-special-interview-113610.html",
      "https://www.baristamagazine.com/brewing-experiments-filip-kucharczyks-world-aeropress-championship-recipe/",
      "https://aeroprecipe.com/recipes/2016-wac-1st-place",
    ],
  },
  {
    id: "wac-2015-1",
    year: 2015,
    place: 1,
    name: "Lukas Zahradnik",
    country: "Slovakia",
    recipe: {
      method: "Inverted",
      filter: "Paper",
      dose_g: 20,
      water_g: 230,
      temp_c: 79,
      grinder: "Mahlkönig EK43",
      grind_setting: "7.3",
      water_recipe: null,
      bloom_water_g: 60,
      bloom_ends_s: 30,
      agitation: "Turbulent wiggle (shake) for 15 seconds after the first 60 g",
      press_starts_s: 40,
      press_duration_s: 45,
      bypass_g: null,
      bypass_temp: null,
      other_steps: "Preheat all the AeroPress parts with 79 °C water for at least 15 seconds. Grind 20 g at 7.3 on an EK43. Inverted: pour 60 g of 79 °C water and give it a turbulent wiggle for 15 seconds; the bloom lasts 30 seconds in total. Add the remaining 170 g of water over 10 seconds, put the cap on, flip and press for 45 seconds. European Coffee Trip gives a total brew time of 1:30.",
    },
    notes: "Slovakia's first WAC title; Zahradnik competed for Green Plantation Coffee (Komárno). The aeropress.com recipe page is now titled 'Lukas Lot'. He recommends a Kenyan coffee, or any dense washed coffee.",
    caveats: "The press start (0:40) is worked out from the stated steps (30 s bloom, then 170 g over 10 s, then flip); no source gives it as a timestamp. Sprudge's wording ('turbulent wiggle for 15 seconds, allow 30 seconds of bloom') could be read as a 45 s bloom; the official listing and European Coffee Trip both give 30 s in total. One aggregator summary gave the second pour as 200 g; the official listing says 170 g (230 g in total). The bypass is left empty: no dilution is mentioned. Water type not published.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/1st-lukas-zahradnik-slovakia-2015",
      "https://worldaeropresschampionship.com/pages/recipes",
      "https://europeancoffeetrip.com/how-to-make-aeropress-2015-champion/",
      "https://sprudge.com/lukas-zahradnik-is-your-2015-world-aeropress-champion-75152.html",
    ],
  },
  {
    id: "wac-2015-2",
    year: 2015,
    place: 2,
    name: "Nick Hatch",
    country: "Canada",
    recipe: {
      method: "Standard",
      filter: "Paper",
      dose_g: 17.5,
      water_g: 260,
      temp_c: 85,
      grinder: "Baratza Virtuoso",
      grind_setting: "17",
      water_recipe: null,
      bloom_water_g: null,
      bloom_ends_s: 25,
      agitation: "Stir 5 times after the first pour",
      press_starts_s: 45,
      press_duration_s: 60,
      bypass_g: null,
      bypass_temp: null,
      other_steps: "Grind 17.5 g at 17 on a Baratza Virtuoso. Upright AeroPress, paper filter, water at 85 °C. Add 50-60 g of water and stir five times. Allow 25 seconds of bloom. Add the rest of the water (to 260 g) over 20 seconds. Press down for 60 seconds into a chilled cup. Total brew time 1:45.",
    },
    notes: "Presses into a chilled cup.",
    caveats: "The bloom water is left empty because the recipe gives a range (50-60 g). The press start (0:45) is worked out from the stated steps (25 s bloom + 20 s pour) and matches the listed 1:45 total with the 60 s press. The bypass is left empty: no dilution is mentioned. Water type not published.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/2nd-nick-hatch-canada-2015",
      "https://worldaeropresschampionship.com/pages/2nd-nick-hatch-canada-2015",
      "https://aeroprecipe.com/recipes/nick-hatch-2015-wac-2nd-place",
    ],
  },
  {
    id: "wac-2015-3",
    year: 2015,
    place: 3,
    name: "Kaye Joy Ong",
    country: "Philippines",
    recipe: {
      method: "Inverted",
      filter: "Paper",
      dose_g: 22.5,
      water_g: 280,
      temp_c: 79,
      grinder: "Mahlkönig EK43",
      grind_setting: "4",
      water_recipe: null,
      bloom_water_g: 56,
      bloom_ends_s: 30,
      agitation: null,
      press_starts_s: null,
      press_duration_s: 30,
      bypass_g: null,
      bypass_temp: null,
      other_steps: "Grind 22.5 g at 4 on an EK43. Heat the water to 79 °C. Inverted AeroPress, paper filter. Add 56 g of water and allow 30 seconds of bloom. Add the rest of the water (to 280 g) over 60 seconds. Press down for 30 seconds.",
    },
    notes: null,
    caveats: "The press start is left empty: the steps add up to 2:00 (30 s bloom + 60 s pour + 30 s press) but the listed total brew time is 1:35, and no flip time is given. No agitation, dilution or water type is published.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/3rd-kaye-joy-ong-phillipines-2015",
      "https://worldaeropresschampionship.com/pages/3rd-kaye-joy-ong-phillipines-2015",
    ],
  },
  {
    id: "wac-2014-1",
    year: 2014,
    place: 1,
    name: "Shuichi Sasaki",
    country: "Japan",
    recipe: {
      method: "Standard",
      filter: "Paper, rinsed with warm water",
      dose_g: 16.5,
      water_g: 250,
      temp_c: 78,
      grinder: "Mahlkönig EK43",
      grind_setting: "9.5",
      water_recipe: "Soft mineral water",
      bloom_water_g: 40,
      bloom_ends_s: 25,
      agitation: "Stir 5 times after the 25-second bloom; stir once after adding the remaining 210 g",
      press_starts_s: null,
      press_duration_s: 75,
      bypass_g: null,
      bypass_temp: null,
      other_steps: "Grind 16.5 g at 9.5 on an EK43. Rinse the paper filter with warm water. Heat soft mineral water to 78 °C. Upright AeroPress. Add 40 g of water and let it bloom for 25 seconds, then stir 5 times. Add 210 g of water and stir once. Press down very slowly for 75 seconds, leaving about 45 g of slurry in the AeroPress.",
    },
    notes: "Sasaki competed for Paul Bassett (Japan). Held in Rimini, Italy, among 27 national champions. The official listing gives a total brew time of 1:40.",
    caveats: "The press start is left empty: no time is given for the 210 g pour or the start of the press, and the listed 1:40 total doesn't add up with a 25 s bloom plus a 75 s press. The bypass is left empty: no dilution is mentioned.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/1st-shuichi-sasaki-japan-2014",
      "https://dailycoffeenews.com/2014/06/13/how-to-brew-the-worlds-best-aeoropress-the-2014-world-champions-recipe/",
      "https://sprudge.com/world-aeropress-championship-57585.html",
    ],
  },
  {
    id: "wac-2014-2",
    year: 2014,
    place: 2,
    name: "Martin Karabinos",
    country: "Slovakia",
    recipe: {
      method: "Standard",
      filter: "Paper",
      dose_g: 18.5,
      water_g: 215,
      temp_c: null,
      grinder: "Mahlkönig EK43",
      grind_setting: "6.2",
      water_recipe: null,
      bloom_water_g: 80,
      bloom_ends_s: 180,
      agitation: "Stir well after the 35 °C water; stir once after the 92 °C water",
      press_starts_s: null,
      press_duration_s: 30,
      bypass_g: null,
      bypass_temp: null,
      other_steps: "Grind 18.5 g at 6.2 on an EK43. Heat some water to 35 °C and the rest to 92 °C. Upright AeroPress with a paper filter. Add 80 g of 35 °C water, stir well, close the AeroPress and leave it for three minutes. Add 135 g of 92 °C water and stir once. Press down slowly for 30 seconds. Total brew time 3:30.",
    },
    notes: "Karabinos competed for Dublin Cafe. The first 80 g is a long, cool (35 °C) pre-infusion rather than a usual bloom.",
    caveats: "The temperature is left empty because the recipe uses two temperatures (80 g at 35 °C, then 135 g at 92 °C). The bloom end is the recipe's 'leave for three minutes', counted from the first pour. The press start is left empty: no time is given for the second pour and stir (the 3:30 total implies about 3:00). The bypass is left empty: no dilution is mentioned. Water type not published.",
    sources: [
      "https://worldaeropresschampionship.com/pages/2nd-martin-karabinos-slovakia-2014",
      "https://sprudge.com/world-aeropress-championship-57585.html",
    ],
  },
  {
    id: "wac-2014-3",
    year: 2014,
    place: 3,
    name: "Jeff Verellen",
    country: "Belgium",
    recipe: {
      method: "Inverted",
      filter: "Paper",
      dose_g: 17.5,
      water_g: 270,
      temp_c: null,
      grinder: "Mahlkönig EK43",
      grind_setting: "8, super-fines sifted out",
      water_recipe: "Spa Blue mineral water (soft, dry residue 33, pH 6.6)",
      bloom_water_g: 40,
      bloom_ends_s: 30,
      agitation: "Shake lightly during the bloom if there are dry spots",
      press_starts_s: 90,
      press_duration_s: 30,
      bypass_g: null,
      bypass_temp: null,
      other_steps: "Pick out beans that are pale, too big, too small or ear-shaped. Grind 17.5 g at 8 on an EK43, tip the grounds into a Sowden Softbrew filter and bang and shake it to get rid of the super-fines. Inverted AeroPress. Add around 40 g of 82 °C water, wetting all the grounds evenly, and let it bloom for 30 seconds, shaking lightly if there are dry spots. Add 230 g of 76 °C water in an extremely slow pour that takes 60 seconds. Press down gently for 30 seconds, leaving about 50 g of slurry in the AeroPress. Total brew time 2:00.",
    },
    notes: "The 2013 champion finishing third the following year.",
    caveats: "The temperature is left empty because two temperatures are used (82 °C bloom, 76 °C main pour). The bloom water is the recipe's 'around 40 g'. The press start (1:30) is worked out from the stated steps (30 s bloom + 60 s pour, total 2:00); the recipe is listed as inverted but doesn't describe the flip. The bypass is left empty: no dilution is mentioned.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/3rd-jeff-verellen-belgium-2014",
      "https://worldaeropresschampionship.com/pages/3rd-jeff-verellen-belgium-2014",
      "https://sprudge.com/world-aeropress-championship-57585.html",
    ],
  },
  {
    id: "wac-2013-1",
    year: 2013,
    place: 1,
    name: "Jeff Verellen",
    country: "Belgium",
    recipe: {
      method: "Standard",
      filter: "Paper, rinsed",
      dose_g: 17,
      water_g: 270,
      temp_c: null,
      grinder: null,
      grind_setting: null,
      water_recipe: "Soft water (Spa) with a high pH",
      bloom_water_g: 50,
      bloom_ends_s: 40,
      agitation: "Light agitation by holding the AeroPress and shaking it a bit",
      press_starts_s: null,
      press_duration_s: 30,
      bypass_g: null,
      bypass_temp: null,
      other_steps: "AeroPress in the regular (upright) position with a rinsed paper filter. Bloom for 40 seconds with 50 ml of water. Add 220 g of water at 79 °C (270 g in total): lightly agitate by holding the AeroPress and shaking it a bit, and add the water very slowly, over about 30 seconds. Press very gently for about 30 seconds, leaving about 50 g (water and coffee) in the brewer.",
    },
    notes: "Held in Melbourne in May 2013. Verellen's second title (he also won in 2011), the first time anyone won the WAC twice.",
    caveats: "The temperature is left empty because the recipe gives two temperatures: the water is listed at 83-84 °C, and the 220 g main pour at 79 °C. The bloom water converts '50 ml' at 1 ml = 1 g. The press start is left empty: the main pour takes 'about 30 seconds' after the 40 s bloom and the agitation has no stated time, so no press start is given. The press time is the recipe's 'about 30 seconds'. Grind not published.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/1st-jeff-verellen-belgium-2013",
      "https://worldaeropresschampionship.com/pages/1st-jeff-verellen-belgium-2013",
      "https://sprudge.com/jeff-verellen-world-aeropress-champion-38796.html",
    ],
  },
  {
    id: "wac-2012-1",
    year: 2012,
    place: 1,
    name: "Charlene de Buysere",
    country: "Belgium",
    recipe: {
      method: "Standard",
      filter: "Paper, rinsed",
      dose_g: 18.3,
      water_g: 250,
      temp_c: 85,
      grinder: null,
      grind_setting: "Coarse",
      water_recipe: null,
      bloom_water_g: 40,
      bloom_ends_s: 30,
      agitation: null,
      press_starts_s: null,
      press_duration_s: null,
      bypass_g: 0,
      bypass_temp: null,
      other_steps: "Wet the paper filter thoroughly and put it in the filter cap. Grind 18.3 g coarsely. Use the normal (non-inverted) method with 250 g of water at 85 °C. Bloom with about 40 g of water for about 30 seconds. Pour the rest of the water and press, not pressing all the way. Serve.",
    },
    notes: "A notably simple recipe.",
    caveats: "Bloom figures are the recipe's approximations ('about 40 grams', '+/- 30 sec'). No timing is given for the main pour or the press, so the press start and the press time are left empty. Grinder, water type and agitation were not published.",
    sources: [
      "https://worldaeropresschampionship.com/pages/1st-charlene-de-buysere-belgium-2012",
      "https://aeromatic.app/recipes/wac-2012-winner-aeropress-recipe",
      "https://bigcupofcoffee.com/winning-aeropress-champion-recipes/",
    ],
  },
  {
    id: "wac-2011-1",
    year: 2011,
    place: 1,
    name: "Jeff Verellen",
    country: "Belgium",
    recipe: {
      method: "Standard",
      filter: "Paper, wetted with hot water",
      dose_g: 17,
      water_g: 270,
      temp_c: 80,
      grinder: null,
      grind_setting: "Coarse (coarser than for paper filter)",
      water_recipe: "Soft mineral water or filtered water",
      bloom_water_g: 40,
      bloom_ends_s: 30,
      agitation: null,
      press_starts_s: null,
      press_duration_s: null,
      bypass_g: null,
      bypass_temp: null,
      other_steps: "Put the paper filter in the cap, wet it with hot water, let it expand, refit it and screw it very tightly onto a clean, preferably preheated AeroPress. Grind 17 g coarsely (a bit coarser than for paper filter) at the last moment. Stand the AeroPress non-inverted on the cup. Heat 270 g of soft mineral or filtered water to 80 °C. Splash a little water on the filter, then add the coffee straight away so the bottom wets and expands. Wet all the grounds by dripping or pouring very slowly, about 40 g. When the coffee has absorbed the water, after about 30 seconds, pour the rest very slowly, re-wetting the coffee fully and keeping the grounds from separating from the water. Steep for one minute. Push the plunger a quarter of the way in, then press about half of the remaining water through. Take the AeroPress off the cup and throw away the rest.",
    },
    notes: "No stirring: the grounds are wetted by the slow pours. Only part of the brew is pressed into the cup. Verellen won again in 2013.",
    caveats: "The bloom water and the bloom end are the recipe's approximate figures ('about 40 grams', 'after about 30 seconds'). The press start is left empty: the one-minute steep starts after a very slow pour of unstated length. The press time is left empty (not stated). The bypass is left empty: no dilution is mentioned; the leftover brew is discarded. Grinder not published.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/1st-jeff-verellen-belgium-2011",
      "https://sprudge.com/today-the-world-aeropress-championship-2011-13462.html",
      "https://www.moustachecoffeeclub.com/best-aeropress-recipes",
    ],
  },
  {
    id: "wac-2010-1",
    year: 2010,
    place: 1,
    name: "Marie Hagemeister",
    country: "Denmark",
    recipe: {
      method: "Inverted",
      filter: "Paper, soaked with hot water",
      dose_g: 20,
      water_g: null,
      temp_c: 80,
      grinder: null,
      grind_setting: "Slightly finer than filter",
      water_recipe: null,
      bloom_water_g: 0,
      bloom_ends_s: 0,
      agitation: "Stir for 10-12 seconds after the pour",
      press_starts_s: null,
      press_duration_s: null,
      bypass_g: 0,
      bypass_temp: null,
      other_steps: "Boil the water so it is 80 °C when it goes on the coffee. Grind 20 g slightly finer than filter. Invert the AeroPress and soak the paper filter with hot water. Add the coffee and pour the 80 °C water over it, almost to the top. Stir for 10-12 seconds. Heat the cup, then slowly push the coffee into the cup, stopping before you hear air. Serve.",
    },
    notes: "Held in London; the first woman to win the WAC. Her first name also appears as 'Maria' on some WAC pages; the aeropress.com recipe page and Sprudge use 'Marie'. No bloom: all the water goes in with one pour.",
    caveats: "The water is left empty: the recipe only says to fill 'almost to the top'. No steep or press timing is given beyond the 10-12 s stir, so the press start and the press time are left empty. Grinder and water type were not published.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/1st-marie-hagemeister-denmark-2010",
      "https://sprudge.com/aeropress-champion-marie-hagemeisters-winning-brew-method-3075.html",
      "https://worldaeropresschampionship.com/pages/2010-world-final",
    ],
  },
  {
    id: "wac-2009-1",
    year: 2009,
    place: 1,
    name: "Lukasz Jura",
    country: "Poland",
    recipe: {
      method: "Inverted",
      filter: "Paper, soaked",
      dose_g: null,
      water_g: 200,
      temp_c: 75,
      grinder: null,
      grind_setting: "Slightly coarser than filter",
      water_recipe: null,
      bloom_water_g: null,
      bloom_ends_s: null,
      agitation: "Stir 4 times",
      press_starts_s: 10,
      press_duration_s: null,
      bypass_g: 0,
      bypass_temp: null,
      other_steps: "Inverted AeroPress with a soaked paper filter. 19.5-20 g of coffee ground slightly coarser than filter, 200 ml of water at 75 °C. Stir 4 times. Stop stirring, secure the filter (cap) and turn the AeroPress over at around 10 seconds; total contact time is around 15 seconds. Press and serve.",
    },
    notes: "A very short brew: about 15 seconds of contact time in total. The recipe gives the water in millilitres; the water uses 1 ml = 1 g.",
    caveats: "The dose is left empty because the recipe gives a range (19.5-20 g). The water is converted from '200 ml'. The press start is the recipe's 'around 10 seconds'. The pour itself isn't described, so the bloom fields are left empty (with 15 s of total contact there is no bloom step). Press duration, grinder and water type were not published.",
    sources: [
      "https://aeropress.com/blogs/w-a-c-aeropress-recipes/1st-lukasz-jura-poland-2009",
      "https://worldaeropresschampionship.com/pages/1st-lukasz-jura-poland-2009",
      "https://www.moustachecoffeeclub.com/best-aeropress-recipes",
    ],
  },
  {
    id: "wac-2008-1",
    year: 2008,
    place: 1,
    name: "Anders Valde",
    country: "Norway",
    recipe: null,
    notes: "The first WAC, held in Oslo with three competitors.",
    caveats: "No recipe was ever published: the official WAC page for this entry says 'Recipe not available', and no other source gives one.",
    sources: [
      "https://worldaeropresschampionship.com/pages/past-championships",
      "https://worldaeropresschampionship.com/pages/1st-anders-valde-norway-2008",
      "https://perfectdailygrind.com/2019/03/the-history-of-the-aeropress-from-concept-to-championships/",
    ],
  },
];
