// Every string the UI shows lives here, so an Arabic version can be added later
// by providing the same shape in another language.

const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`;

export const strings = {
  app: {
    name: 'AeroPress Lab',
    loading: 'Loading…',
  },

  tabs: {
    board: 'Board',
    beans: 'Beans',
    recipes: 'Recipes',
    brew: 'Brew',
    duel: 'Duel',
    coach: 'Coach',
    label: 'Main sections',
  },

  common: {
    back: 'Back',
    cancel: 'Cancel',
    close: 'Close',
    show: 'Show',
    hide: 'Hide',
    retry: 'Try again',
    saving: 'Saving…',
    owner: 'Owner',
    barista: 'Barista',
    you: 'You',
    edit: 'Edit',
    none: '—',
  },

  units: {
    g: 'g',
    celsius: '°C',
    seconds: 's',
    percent: '%',
  },

  setup: {
    title: 'Set up your team',
    intro: 'You only do this once. You become the owner; everyone else joins as a barista.',
    teamName: 'Team name',
    teamNamePlaceholder: 'e.g. Kurdi Coffee Lab',
    ownerName: 'Your name',
    ownerNamePlaceholder: 'e.g. Abdelrahman Kurdi',
    ownerPin: 'Owner PIN',
    ownerPinHint: 'Only you use this. It unlocks the owner settings. 4 to 8 digits.',
    ownerPinRepeat: 'Repeat owner PIN',
    teamPin: 'Team PIN',
    teamPinHint: 'Baristas sign in with this. Use 6 digits or more, and not your owner PIN.',
    teamPinRepeat: 'Repeat team PIN',
    submit: 'Create team',
    submitting: 'Creating team…',
    teamNameRequired: 'Enter a team name.',
    ownerNameRequired: 'Enter your name.',
    pinFormat: 'PINs are 4 to 8 digits.',
    ownerPinMismatch: 'The two owner PINs don’t match. Type them again.',
    teamPinMismatch: 'The two team PINs don’t match. Type them again.',
    pinsMustDiffer: 'The owner PIN and the team PIN must be different.',
  },

  signIn: {
    whoIsBrewing: 'Who’s brewing?',
    pickName: 'Tap your name to sign in.',
    noMembers: 'No one is on the team yet.',
    notYou: 'Not you?',
    hi: (name: string) => `Hi, ${name.split(' ')[0] ?? name}`,
    enterOwnerPin: 'Enter your owner PIN',
    enterPersonalPin: 'Enter your PIN',
    enterTeamPin: 'Enter the team PIN',
    submit: 'Sign in',
    submitting: 'Signing in…',
    deleteDigit: 'Delete last digit',
    digitsEntered: (n: number) => `${plural(n, 'digit', 'digits')} entered`,
  },

  shell: {
    openSettings: 'Settings and sign out',
    offline: 'Offline',
    brewRunning: 'timer running',
  },

  board: {
    title: 'Board',
    greeting: (name: string) => `Hi, ${name.split(' ')[0] ?? name}`,
    addTeamTitle: 'Add your baristas',
    addTeamBody: 'Add everyone who trains with you. They sign in with the team PIN.',
    addTeamAction: 'Add baristas',
    emptyTitle: 'Dashboard comes later',
    emptyBody: 'Beans and recipes are in the tabs below. Progress charts, consistency and the readiness checklist arrive in phase 6.',
  },

  comingSoon: {
    duel: { title: 'Duel', body: 'Blind multi-phone duels and Elo ranking arrive in phase 4.' },
    coach: { title: 'Coach', body: 'The AI coach arrives in phase 5.' },
    label: 'Coming soon',
  },

  settings: {
    title: 'Settings',
    unsyncedWarning: (n: number) =>
      `${plural(n, 'brew on this phone hasn’t', 'brews on this phone haven’t')} synced yet. ${n === 1 ? 'It stays' : 'They stay'} here and ${n === 1 ? 'syncs' : 'sync'} next time you sign in on this phone.`,
    you: 'You',
    theme: 'Theme',
    themeSystem: 'System',
    themeLight: 'Light',
    themeDark: 'Dark',
    team: 'Team',
    members: 'Members',
    membersCount: (n: number) => plural(n, 'active member', 'active members'),
    changeTeamPin: 'Change team PIN',
    changeTeamPinBody: 'Baristas who sign in with the team PIN use the new one from their next sign-in. Anyone signed in now stays signed in.',
    newTeamPin: 'New team PIN',
    saveTeamPin: 'Save team PIN',
    teamPinSaved: 'Team PIN changed.',
    importV1: 'Import v1 backup',
    importV1Sub: 'Bring in beans, recipes, brews and duels from the old app',
    signOut: 'Sign out',
    signingOut: 'Signing out…',
    signOutOffline: 'Signing out needs a connection. Try again once you’re online.',
  },

  members: {
    title: 'Members',
    addTitle: 'Add a barista',
    addName: 'Name',
    addNamePlaceholder: 'e.g. Lina Haddad',
    addSubmit: 'Add barista',
    nameRequired: 'Enter their name.',
    added: (name: string) => `${name} added. They sign in with the team PIN.`,
    active: 'Active',
    inactive: 'Deactivated',
    locked: 'Locked',
    signsInWith: {
      owner: 'Owner PIN',
      personal: 'Own PIN',
      team: 'Team PIN',
    },
    lockedFor: (minutes: number) => `Locked for ${plural(minutes, 'minute', 'minutes')}`,
    sheet: {
      signsInWith: 'Signs in with',
      resetPin: 'Reset PIN',
      resetPinBody: (name: string) =>
        `Give ${name} a personal PIN. They sign in with it instead of the team PIN, and they’re signed out on their other phones.`,
      changeOwnerPin: 'Change owner PIN',
      changeOwnerPinBody: 'You stay signed in here. Other phones signed in as you are signed out.',
      newPin: 'New PIN',
      savePersonalPin: 'Set personal PIN',
      saveOwnerPin: 'Save owner PIN',
      pinSaved: 'PIN saved.',
      useTeamPin: 'Use the team PIN again',
      useTeamPinBody: 'Removes their personal PIN.',
      usingTeamPin: 'They sign in with the team PIN again.',
      deactivate: 'Deactivate',
      deactivateNamed: (name: string) => `Deactivate ${name}`,
      deactivateBody: 'Signs them out everywhere and hides them from the sign-in list. Their brews and recipes stay.',
      reactivate: 'Reactivate',
      reactivateNamed: (name: string) => `Reactivate ${name}`,
      reactivateBody: 'Puts them back on the sign-in list.',
      deactivated: (name: string) => `${name} is deactivated.`,
      reactivated: (name: string) => `${name} is back on the team.`,
    },
  },

  beans: {
    title: 'Beans',
    add: 'Add bean',
    emptyTitle: 'No beans yet',
    emptyBody: 'Add the coffees you train with, and mark the competition coffee when you know it.',
    compTag: 'Comp',
    competition: 'Competition coffee',
    daysOff: (n: number) => (n === 0 ? 'Roasted today' : n < 0 ? 'Roast date is ahead' : `${plural(n, 'day', 'days')} off roast`),
    /** Caption under the big day count in the bean list. */
    daysOffLabel: (n: number) => (n < 0 ? 'days until roast' : n === 1 ? 'day off roast' : 'days off roast'),
    noRoastDate: 'No roast date',
    brews: (n: number) => plural(n, 'brew', 'brews'),
    form: {
      newTitle: 'New bean',
      editTitle: 'Edit bean',
      name: 'Name',
      namePlaceholder: 'e.g. Ethiopia Guji Hambela',
      nameRequired: 'Give the bean a name.',
      roaster: 'Roaster',
      origin: 'Origin',
      originPlaceholder: 'Country, region',
      variety: 'Variety',
      process: 'Process',
      roastLevel: 'Roast level',
      roastDate: 'Roast date',
      altitude: 'Altitude',
      altitudePlaceholder: 'e.g. 2100 m',
      densityNotes: 'Density notes',
      notes: 'Notes',
      notesPlaceholder: 'Tasting notes, how it brews…',
      competition: 'Competition coffee',
      competitionHint: 'The organizer’s coffee for the championship. Only one bean holds this; marking it here clears the others.',
      competitionOwnerOnly: 'Only the owner can change the competition coffee.',
      processOptions: ['Washed', 'Natural', 'Honey', 'Anaerobic', 'Carbonic maceration', 'Wet-hulled'],
      roastOptions: ['Light', 'Medium-light', 'Medium', 'Medium-dark', 'Dark'],
      create: 'Add bean',
      save: 'Save bean',
    },
  },

  recipes: {
    title: 'Recipes',
    new: 'New recipe',
    newShort: 'New',
    mine: 'Mine',
    everyone: 'Everyone',
    scopeLabel: 'Whose recipes',
    allBeans: 'All beans',
    beanLabel: 'Bean',
    beanFilterNote: (bean: string) => `Elo from duels on ${bean} only.`,
    emptyTitle: 'No recipes yet',
    emptyBody: 'Create a recipe to start logging brews and running duels.',
    emptyOwnerBody: 'Create a recipe, or bring in your old data with Settings › Import v1 backup.',
    emptyMine: 'You haven’t created a recipe yet.',
    emptyBean: 'No recipes on this bean yet.',
    elo: 'Elo',
    record: (s: { wins: number; losses: number; draws: number }) => `${s.wins}–${s.losses}–${s.draws}`,
    recordLabel: 'W–L–D',
    noDuels: 'No duels yet',
    duels: (n: number) => plural(n, 'duel', 'duels'),
    rank: (n: number) => `#${n}`,
    compTag: 'Comp',
    untitled: 'Untitled',
    methods: { Inverted: 'Inverted', Standard: 'Standard' } as Record<string, string>,
    fields: {
      name: 'Name',
      bean: 'Bean',
      method: 'Method',
      filter: 'Filter',
      dose: 'Dose',
      water: 'Water',
      ratio: 'Ratio',
      temp: 'Temperature',
      grinder: 'Grinder',
      grind: 'Grind setting',
      waterRecipe: 'Water recipe',
      bloomWater: 'Bloom water',
      bloomEnds: 'Bloom ends at',
      agitation: 'Agitation',
      pressStarts: 'Press starts at',
      pressDuration: 'Press takes',
      bypass: 'Bypass',
      bypassTemp: 'Bypass temperature',
      otherSteps: 'Other steps',
      notes: 'Notes',
      elo: 'Elo',
      record: 'W–L–D',
      owner: 'Created by',
    },
    detail: {
      by: (name: string) => `by ${name}`,
      versionOf: (code: string) => `Version of ${code}`,
      cloneAndTweak: 'Clone and tweak',
      compare: 'Compare',
      lineage: 'Lineage',
      edit: 'Edit',
      lock: 'Lock as competition recipe',
      unlock: 'Unlock competition recipe',
      lockedTag: 'Competition recipe',
      lockedNote: 'Locked as the competition recipe. The owner has to unlock it before it can change.',
      lockedNoteOwner: 'Locked as the competition recipe. Unlock it to make changes.',
      notYours: (name: string) => `Only ${name} or the owner can edit this recipe. Clone it to make your own version.`,
      setup: 'Setup',
      averages: 'Brew averages',
      averagesFrom: (n: number) => `from ${plural(n, 'brew', 'brews')}`,
      noBrews: 'No brews logged for this recipe yet.',
      brews: 'Brews',
      latestOnly: 'Showing the latest 200 brews.',
      scores: {
        sweetness: 'Sweetness',
        acidity: 'Acidity',
        body: 'Body',
        clarity: 'Clarity',
        finish: 'Finish',
        overall: 'Overall',
        tds: 'TDS',
        ey: 'EY',
        time: 'Time',
      },
      overallShort: (v: string) => `Overall ${v}`,
      plannedTime: 'Planned time',
    },
    form: {
      newTitle: 'New recipe',
      cloneTitle: (code: string) => `Clone ${code}`,
      editTitle: (code: string) => `Edit ${code}`,
      cloneBanner: 'Change one or two things only, so the duel tells you what worked.',
      changes: (n: number, code: string) => (n === 0 ? `No changes from ${code} yet` : `${plural(n, 'change', 'changes')} from ${code}`),
      tooManyChanges: 'More than two changes: a duel won’t tell you which one mattered.',
      changed: 'Changed',
      sections: { recipe: 'Recipe', coffee: 'Coffee and water', steps: 'Steps', notes: 'Notes' },
      noBean: 'No bean',
      placeholders: {
        name: 'e.g. Cooler, finer',
        filter: 'e.g. Paper ×2',
        grinder: 'e.g. Comandante C40',
        grind: 'e.g. 24 clicks',
        waterRecipe: 'e.g. Third Wave light',
        agitation: 'e.g. 3 stirs N-S-E-W',
        bypassTemp: 'e.g. room temp',
        time: 'm:ss',
        otherSteps: 'Anything else, in order',
        notes: 'Why this version, and what to listen for',
      },
      timeHint: 'Minutes:seconds from the start, like 1:45.',
      durationHint: 'Seconds or m:ss.',
      timeInvalid: 'Use minutes:seconds, like 1:45.',
      numberInvalid: 'Enter a number, like 18 or 17.5.',
      ratio: (value: string) => `Ratio ${value}`,
      create: 'Save recipe',
      clone: 'Save new version',
      save: 'Save changes',
      history: (code: string, brews: number, duels: number) =>
        `${code} already has ${plural(brews, 'brew', 'brews')} and ${plural(duels, 'duel', 'duels')}. Changing its settings changes what those results mean. To test a change, clone it instead.`,
      cloneInstead: 'Clone instead',
      fixErrors: 'Fix the highlighted fields, then save again.',
    },
    compare: {
      title: 'Compare',
      pickTitle: (code: string) => `Compare ${code} with…`,
      pickAnother: 'Compare with another recipe',
      nothingToCompare: 'There’s no other recipe to compare with yet.',
      setting: 'Setting',
      differs: (n: number) => (n === 0 ? 'Same settings' : `${plural(n, 'setting differs', 'settings differ')}`),
      legend: 'Highlighted rows differ.',
    },
    lineage: {
      title: 'Lineage',
      intro: 'Every version in this family, with its Elo. Tap one to open it.',
      current: 'You are here',
    },
  },

  brew: {
    title: 'Brew',
    pick: 'Pick a recipe to brew.',
    lastBrewed: 'Brewed last on this phone',
    inProgress: (code: string, time: string) => `Brewing ${code} · ${time}`,
    backToTimer: 'Back to the timer',
    planned: (time: string) => `Planned ${time}`,
    fits: 'fits in 5:00',
    over: (time: string) => `${time} over 5:00`,
    incomplete: 'This recipe has no press start or press time, so the timer can’t call the later steps. Add them to the recipe for the full guide.',
    editRecipe: 'Edit recipe',
    missingRecipe: 'That recipe isn’t on this phone yet. Go online once to load your recipes.',
    otherRunning: (code: string) => `A brew of ${code} is still going.`,
    goToOther: (code: string) => `Back to ${code}`,
    stopOther: 'Stop it and brew this',
    start: 'Start',
    pause: 'Pause',
    resume: 'Resume',
    startOver: 'Start over',
    logThis: 'Log this brew',
    logBrew: 'Log a brew',
    brewThis: 'Brew',
    setup: 'Setup',
    steps: 'Steps',
    ready: 'Ready',
    readyDetail: 'Tap Start as the water hits the coffee.',
    done: 'Done',
    doneDetail: 'Taste it, then log it.',
    over5: 'Over 5:00',
    left: (time: string) => `${time} left`,
    next: (title: string, at: string) => `Next: ${title} at ${at}`,
    paused: 'Paused',
    phases: {
      bloom: 'Bloom',
      steep: 'Pour and steep',
      flip: 'Flip',
      press: 'Press',
      bypass: 'Bypass',
      pour: 'Pour',
    } as Record<string, string>,
    phaseDetail: {
      bloom: (grams: string | null) => (grams ? `Pour ${grams} and let it bloom.` : 'Pour and let it bloom.'),
      steep: (water: string | null, agitation: string | null) =>
        [water ? `Pour to ${water}.` : 'Pour the rest.', agitation ? `${agitation}.` : '', 'Cap and steep.'].filter(Boolean).join(' '),
      flip: 'Flip it onto the cup.',
      press: (time: string) => `Press steadily for ${time}.`,
      bypass: (grams: string, temp: string | null) => `Add ${grams} of water${temp ? ` (${temp})` : ''}.`,
      pour: 'Pour into the judging cup.',
    },
    offlineNote: 'You’re offline. The timer works; brews you log wait on this phone and sync later.',
    waitingTitle: (n: number) => `${plural(n, 'brew is', 'brews are')} waiting to sync`,
    waitingBody: (n: number) =>
      n === 1 ? 'It goes up by itself when there’s a connection.' : 'They go up by themselves when there’s a connection.',
    syncNow: 'Sync now',
    refused: (label: string, reason: string) => `${label} couldn’t be saved: ${reason}`,
    discard: 'Discard',
    log: {
      title: 'Log brew',
      bean: 'Bean',
      noBean: 'No bean',
      grind: 'Grind used',
      totalTime: 'Total time',
      tds: 'TDS',
      beverage: 'Beverage weight',
      ey: (value: string) => `Extraction yield ${value}`,
      eyNeeds: 'Extraction yield shows once TDS and beverage weight are in (and the recipe has a dose).',
      scores: 'Scores',
      scoresHint: 'Drag to score from 1 to 10. Leave a score at — to skip it.',
      scoreLabels: {
        sweetness: 'Sweetness',
        acidity: 'Acidity',
        body: 'Body',
        clarity: 'Clarity',
        finish: 'Finish',
        overall: 'Overall',
      },
      unset: '—',
      clear: 'Clear',
      notes: 'Notes',
      notesPlaceholder: 'Hot, warm, cool?',
      outOfRange: (min: string, max: string) => `Enter a number from ${min} to ${max}.`,
      timeTooLong: (max: string) => `Enter a time up to ${max}.`,
      save: 'Save brew',
      saved: 'Brew saved.',
      queued: 'Brew saved on this phone.',
    },
  },

  importV1: {
    title: 'Import v1 backup',
    intro: 'Pick the JSON backup exported from the old AeroPress Lab. Everything comes in as yours, and anything already here is skipped, so importing twice is safe.',
    choose: 'Choose backup file',
    chooseAnother: 'Choose a different file',
    reading: 'Reading the file…',
    fileErrors: {
      not_json: 'That file isn’t a JSON backup. Export the backup again from the old app and pick that file.',
      not_v1: 'That file isn’t an AeroPress Lab backup. Pick the file the old app exported.',
      wrong_version: 'That backup comes from a different version of the app. This import reads v1 backups.',
    } as Record<string, string>,
    readyTitle: 'Ready to import',
    fileName: (name: string) => `From ${name}`,
    kinds: { beans: 'Beans', recipes: 'Recipes', brews: 'Brews', duels: 'Duels', settings: 'Championship details' } as Record<string, string>,
    settingsFound: 'Championship name, date and competition coffee notes',
    checkTitle: 'Worth knowing before you import',
    planWarnings: {
      missing_id: (n: number) => `${plural(n, 'record has', 'records have')} no id; each gets a fixed one so re-importing stays safe.`,
      duplicate_id: (n: number) => `${plural(n, 'record repeats', 'records repeat')} an id; only the first copy comes in.`,
      not_a_record: (n: number) => `${plural(n, 'entry isn’t', 'entries aren’t')} a record and will be skipped.`,
      unnamed_bean: (n: number) => `${plural(n, 'bean has', 'beans have')} no name and will be called “Unnamed bean”.`,
      bad_number: (n: number) => `${plural(n, 'number', 'numbers')} couldn’t be read and will be left empty.`,
      bad_time: (n: number) => `${plural(n, 'time', 'times')} couldn’t be read (expected m:ss) and will be left empty.`,
      bad_date: (n: number) => `${plural(n, 'date', 'dates')} couldn’t be read and will be left empty.`,
      score_out_of_range: (n: number) => `${plural(n, 'score is', 'scores are')} outside 1–10 and will be left empty.`,
      method_defaulted: (n: number) => `${plural(n, 'recipe has', 'recipes have')} no method we recognise, so ${n === 1 ? 'it’s' : 'they’re'} set to Inverted. Check after importing.`,
      lineage_loop: (n: number) => `${plural(n, 'lineage loops', 'lineages loop')} back on itself; the loop will be cut.`,
      parent_not_in_file: (n: number) => `${plural(n, 'recipe was', 'recipes were')} cloned from a recipe that isn’t in this file.`,
      bean_not_in_file: (n: number) => `${plural(n, 'record names', 'records name')} a bean that isn’t in this file.`,
      recipe_not_in_file: (n: number) => `${plural(n, 'record names', 'records name')} a recipe that isn’t in this file.`,
      'brews:recipe_not_in_file': (n: number) =>
        `${plural(n, 'brew names', 'brews name')} a recipe that isn’t in this file; ${n === 1 ? 'it comes' : 'they come'} in without a recipe.`,
      'duels:recipe_not_in_file': (n: number) =>
        `${plural(n, 'duel names', 'duels name')} a recipe that isn’t in this file; ${n === 1 ? 'it’s' : 'they’re'} left out of the ranking.`,
      'recipes:bean_not_in_file': (n: number) => `${plural(n, 'recipe names', 'recipes name')} a bean that isn’t in this file.`,
      'brews:bean_not_in_file': (n: number) => `${plural(n, 'brew names', 'brews name')} a bean that isn’t in this file.`,
      'duels:bean_not_in_file': (n: number) => `${plural(n, 'duel names', 'duels name')} a bean that isn’t in this file.`,
      duel_missing_recipe: (n: number) => `${plural(n, 'duel is', 'duels are')} missing a recipe and will be skipped.`,
      duel_bad_winner: (n: number) => `${plural(n, 'duel names', 'duels name')} a winner that wasn’t in the duel and will be skipped.`,
    } as Record<string, (n: number) => string>,
    ignoredTitle: 'Fields this app doesn’t use (left out)',
    ignoredField: (kind: string, field: string, n: number) => `${kind}.${field} (${n})`,
    start: 'Import everything',
    progress: (kind: string, done: number, total: number) => `Importing ${kind.toLowerCase()}… ${done} of ${total}`,
    doneTitle: 'Import finished',
    resultLine: (inserted: number, already: number, skipped: number) =>
      [
        `${inserted} added`,
        already ? `${already} already here` : '',
        skipped ? `${skipped} left out` : '',
      ]
        .filter(Boolean)
        .join(' · '),
    serverNotesTitle: 'What changed on the way in',
    serverWarnings: {
      'beans:extra_competition_coffee': (n: number, ex: string[]) =>
        `${plural(n, 'bean was', 'beans were')} also marked as the competition coffee (${ex.join(', ')}). Only one can be; the marker stayed where it was.`,
      'recipes:bean_missing': (n: number) => `${plural(n, 'recipe points', 'recipes point')} to a bean that isn’t in the backup, so ${n === 1 ? 'it has' : 'they have'} no bean now.`,
      'recipes:parent_missing': (n: number) => `${plural(n, 'recipe was', 'recipes were')} cloned from a recipe that isn’t in the backup, so ${n === 1 ? 'it starts' : 'they start'} a new lineage.`,
      'recipes:code_renamed': (n: number, ex: string[]) => `${plural(n, 'recipe code was', 'recipe codes were')} already in use and got the next free number (${ex.join(', ')}).`,
      'recipes:extra_lock': (n: number) => `${plural(n, 'more recipe was', 'more recipes were')} marked as the competition recipe. Only one can be locked, so ${n === 1 ? 'it was' : 'they were'} left unlocked.`,
      'brews:recipe_missing': (n: number) => `${plural(n, 'brew belongs', 'brews belong')} to a recipe that isn’t in the backup. ${n === 1 ? 'It was' : 'They were'} kept without a recipe.`,
      'brews:bean_missing': (n: number) => `${plural(n, 'brew names', 'brews name')} a bean that isn’t in the backup, so ${n === 1 ? 'it has' : 'they have'} no bean now.`,
      'duels:recipe_missing': (n: number) => `${plural(n, 'duel', 'duels')} involved a recipe that isn’t in the backup, so ${n === 1 ? 'it was' : 'they were'} left out of the ranking.`,
      'duels:bad_winner': (n: number) => `${plural(n, 'duel names', 'duels name')} a winner that wasn’t in the duel, so ${n === 1 ? 'it was' : 'they were'} left out.`,
      'duels:bean_missing': (n: number) => `${plural(n, 'duel names', 'duels name')} a bean that isn’t in the backup, so ${n === 1 ? 'it has' : 'they have'} no bean now.`,
    } as Record<string, (n: number, examples: string[]) => string>,
    failed: (message: string) =>
      `The import stopped: ${message} Everything before that is saved. Tap Import everything to carry on; records already imported are skipped.`,
    seeRecipes: 'See recipes',
    seeBeans: 'See beans',
  },

  errors: {
    offline: 'You’re offline. Check the connection and try again.',
    timeout: 'The connection is too slow right now. Try again in a moment.',
    generic: 'Something went wrong. Try again in a moment.',
    loadFailed: 'Couldn’t load the app. Check the connection and try again.',
    // Keyed by API error code. Functions receive the error body.
    byCode: {
      not_signed_in: 'You’re signed out. Sign in again to continue.',
      owner_only: 'Only the owner can do this.',
      wrong_pin: (e: { tries_left?: number }) =>
        e.tries_left === undefined
          ? 'Wrong PIN. Try again.'
          : `Wrong PIN. ${plural(e.tries_left, 'try', 'tries')} left before a 15-minute lock.`,
      locked: (e: { retry_after_ms?: number }) => {
        const minutes = Math.max(1, Math.ceil((e.retry_after_ms ?? 15 * 60_000) / 60_000));
        return `Too many wrong PINs. Try again in ${plural(minutes, 'minute', 'minutes')}.`;
      },
      member_not_found: 'That name is no longer on the team. Go back and pick your name again.',
      already_set_up: 'This team is already set up. Sign in instead.',
      name_taken: 'Someone on the team already has that name. Add a last initial to tell them apart.',
      pin_matches_team: 'The owner PIN must differ from the team PIN. Pick another PIN.',
      pin_matches_owner: 'The team PIN must differ from the owner PIN. Pick another PIN.',
      server_error: 'Something went wrong on our side. Try again in a moment. If it keeps happening, tell the owner.',
      not_found: 'That no longer exists. Go back and refresh the list.',
      bean_not_found: 'That bean no longer exists. Pick another bean.',
      parent_not_found: 'The recipe you cloned no longer exists. Go back to the recipe list.',
      recipe_locked: 'This is the locked competition recipe. The owner has to unlock it before it can change.',
      recipe_not_found: 'That recipe no longer exists. Pick another recipe.',
      brew_id_taken: 'This brew clashes with another one. Log it again as a new brew.',
      wrong_member: 'Someone else logged this brew on this phone. It syncs when they sign in here again.',
    } as Record<string, string | ((e: Record<string, unknown>) => string)>,
  },
};

export type Strings = typeof strings;
