// Every string the UI shows lives here, so an Arabic version can be added later
// by providing the same shape in another language.
import type { CompareFraming } from '../../shared/types';

const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`;

export const strings = {
  app: {
    name: 'AeroPress Lab',
    loading: 'Loading…',
  },

  tabs: {
    board: 'Board',
    beans: 'Beans',
    recipes: 'Recipes',
    brew: 'Brew',
    duel: 'Duel',
    coach: 'Coach',
    label: 'Main sections',
  },

  common: {
    back: 'Back',
    cancel: 'Cancel',
    close: 'Close',
    show: 'Show',
    hide: 'Hide',
    retry: 'Try again',
    saving: 'Saving…',
    owner: 'Owner',
    barista: 'Barista',
    you: 'You',
    edit: 'Edit',
    none: '—',
  },

  units: {
    g: 'g',
    celsius: '°C',
    seconds: 's',
    percent: '%',
  },

  setup: {
    title: 'Set up your team',
    intro: 'You only do this once. You become the owner; everyone else joins as a barista.',
    teamName: 'Team name',
    teamNamePlaceholder: 'e.g. Kurdi Coffee Lab',
    ownerName: 'Your name',
    ownerNamePlaceholder: 'e.g. Abdelrahman Kurdi',
    ownerPin: 'Owner PIN',
    ownerPinHint: 'Only you use this. It unlocks the owner settings. 4 to 8 digits.',
    ownerPinRepeat: 'Repeat owner PIN',
    teamPin: 'Team PIN',
    teamPinHint: 'Baristas sign in with this. Use 6 digits or more, and not your owner PIN.',
    teamPinRepeat: 'Repeat team PIN',
    submit: 'Create team',
    submitting: 'Creating team…',
    teamNameRequired: 'Enter a team name.',
    ownerNameRequired: 'Enter your name.',
    pinFormat: 'PINs are 4 to 8 digits.',
    ownerPinMismatch: 'The two owner PINs don’t match. Type them again.',
    teamPinMismatch: 'The two team PINs don’t match. Type them again.',
    pinsMustDiffer: 'The owner PIN and the team PIN must be different.',
  },

  signIn: {
    whoIsBrewing: 'Who’s brewing?',
    pickName: 'Tap your name to sign in.',
    noMembers: 'No one is on the team yet.',
    notYou: 'Not you?',
    hi: (name: string) => `Hi, ${name.split(' ')[0] ?? name}`,
    enterOwnerPin: 'Enter your owner PIN',
    enterPersonalPin: 'Enter your PIN',
    enterTeamPin: 'Enter the team PIN',
    submit: 'Sign in',
    submitting: 'Signing in…',
    deleteDigit: 'Delete last digit',
    digitsEntered: (n: number) => `${plural(n, 'digit', 'digits')} entered`,
  },

  shell: {
    openSettings: 'Settings and sign out',
    offline: 'Offline',
    brewRunning: 'timer running',
  },

  board: {
    title: 'Board',
    greeting: (name: string) => `Hi, ${name.split(' ')[0] ?? name}`,
    addTeamTitle: 'Add your baristas',
    addTeamBody: 'Add everyone who trains with you. They sign in with the team PIN.',
    addTeamAction: 'Add baristas',
    whose: 'Whose board',
    team: 'Whole team',
    offline: 'The Board needs a connection. The timer and brew log work offline.',
    // Countdown
    daysLeft: (n: number) => (n === 1 ? 'day' : 'days'),
    toChamp: (name: string | null) => `to ${name ?? 'the championship'}`,
    champToday: 'Championship day',
    champPast: (name: string | null) => `${name ?? 'The championship'} is over`,
    noDate: 'No championship date yet.',
    setDate: 'Set the championship date',
    // Readiness
    readiness: 'Readiness',
    readinessScore: (done: number, of: number) => `${done} of ${of}`,
    readinessItems: {
      locked: 'Competition recipe locked',
      wins: 'Locked recipe has won 5+ duels',
      beans: 'Tested on 2+ beans',
      timed: '5 timed runs in a row under 5:00',
      comp_duel: 'A duel on the competition coffee',
    } as Record<string, string>,
    readinessDetail: {
      locked: (code: string | null) => (code ? code : 'Lock one from its recipe page'),
      wins: (n: number) => `${n} ${n === 1 ? 'win' : 'wins'}`,
      beans: (n: number) => `${n} ${n === 1 ? 'bean' : 'beans'}`,
      timed: (n: number) => `${n} in a row`,
      comp_duel: (n: number) => `${n} ${n === 1 ? 'duel' : 'duels'}`,
      noComp: 'Mark the competition coffee in Beans first',
      needsLock: 'Needs a locked recipe',
    },
    // Top recipe and leaderboard
    topRecipe: 'Top recipe',
    myTopRecipe: 'Your top recipe',
    theirTopRecipe: (name: string) => `${name.split(' ')[0] ?? name}’s top recipe`,
    noTop: 'No duels yet. A recipe ranks here after its first duel.',
    eloLine: (elo: number, record: string) => `Elo ${elo} · ${record}`,
    leaderboard: 'Team leaderboard',
    leaderboardHint: 'Each member’s best recipe.',
    noRecipeYet: 'No duelled recipe yet',
    // Progress
    progress: 'Progress',
    eloOverTime: 'Elo over time',
    eloEmpty: 'The chart starts after the first duel.',
    eloSummary: (code: string, from: number, to: number, duels: number) => `${code}: ${from} to ${to} over ${duels} ${duels === 1 ? 'duel' : 'duels'}`,
    weekly: 'Average overall score per week',
    weeklyEmpty: 'Log brews with an overall score to see the weekly average.',
    weekOf: (label: string) => `Week of ${label}`,
    overall: 'Overall',
    // Consistency
    consistency: 'Consistency',
    consistencyHint: (tds: string, overall: string) =>
      `Spread (standard deviation) for recipes with 3 or more brews in the last 90 days. A spread of ${tds} TDS or ${overall} overall is flagged.`,
    consistencyEmpty: 'Recipes show here once they have 3 brews in the last 90 days.',
    spread: (tds: string | null, overall: string | null) =>
      [tds !== null ? `TDS ±${tds}` : null, overall !== null ? `overall ±${overall}` : null].filter(Boolean).join(' · ') || 'No TDS or scores logged',
    brewsCount: (n: number) => `${n} brews`,
    unreliable: 'Unreliable on stage',
    steady: 'Steady',
    // Volume
    activity: 'Activity, last 30 days',
    activityEmpty: 'No brews or duels in the last 30 days.',
    activityLegend: { brews: 'Brews', duels: 'Duels' },
    memberVolume: (brews: number, duels: number) => `${brews} ${brews === 1 ? 'brew' : 'brews'} · ${duels} ${duels === 1 ? 'duel' : 'duels'}`,
    lastActive: (days: number | null) =>
      days === null ? 'No sessions in the last 30 days' : days === 0 ? 'Active today' : days === 1 ? 'Last session yesterday' : `Last session ${days} days ago`,
    // AI
    ai: 'AI coach this month',
    aiLine: (spent: string, cap: string) => `${spent} of ${cap}`,
    aiCalls: (n: number) => `${n} ${n === 1 ? 'call' : 'calls'}`,
    aiNotConfigured: 'Not set up yet. The README says how to add an OpenRouter (or Anthropic) API key.',
    aiModel: (model: string) => `Coach model: ${model}`,
    aiChange: 'Change the budget',
  },

  coach: {
    title: 'Coach',
    spend: (spent: string, cap: string) => `AI this month: ${spent} of ${cap}`,
    spendModel: (spent: string, cap: string, model: string) => `AI this month: ${spent} of ${cap} · ${model}`,
    notConfigured: 'The AI coach needs an OpenRouter or Anthropic API key. The owner adds it in Cloudflare; the README says how.',
    offline: 'The coach needs a connection. You’re offline.',
    thinking: 'The coach is thinking. This can take up to a minute.',
    thinkingShort: 'Thinking…',
    money: (usd: number) => `$${usd.toFixed(2)}`,
    askEmpty: 'Type a question first.',
    today: 'Today',
    todayLoading: 'Writing today’s session…',
    todayEmpty: 'No duel suggestions today.',
    todayNeedsRecipes: 'Today’s duels start once the team has two recipes.',
    todayWrite: 'Suggest today’s duels',
    startDuel: 'Start this duel',
    versus: (a: string, b: string) => `${a} vs ${b}`,
    plan: 'Plan next session',
    planHint: 'Three experiments to duel against their parents.',
    focus: 'Focus (optional)',
    focusPlaceholder: 'e.g. more sweetness on washed coffees',
    planButton: 'Plan next session',
    adapt: 'Adapt to a new coffee',
    adaptHint: 'Pick the new bean and the recipe to start from. You get three versions of it.',
    adaptBean: 'New coffee',
    adaptRecipe: 'Start from',
    adaptButton: 'Adapt recipe',
    pickBean: 'Pick a bean',
    pickRecipe: 'Pick a recipe',
    needBeanAndRecipe: 'Pick the bean and the recipe first.',
    readiness: 'Readiness',
    readinessHint: 'The coach reads all your data and says how ready you are for championship day.',
    readinessButton: 'Write a readiness report',
    noReport: 'No readiness report yet.',
    verdicts: { ready: 'Ready', close: 'Close', 'not ready': 'Not ready' } as Record<string, string>,
    biggestRisk: 'Biggest risk',
    fixes: 'Three fixes before the championship',
    evidence: 'Evidence',
    reportBy: (name: string, when: string) => `${name} · ${when}`,
    ask: 'Ask anything',
    question: 'Your question',
    askPlaceholder: 'e.g. Why does R3 lose on Kenyan coffees?',
    askButton: 'Ask',
    answer: 'Answer',
    experiments: 'Experiments',
    from: (code: string) => `From ${code}`,
    newRecipe: 'New recipe',
    changes: 'Changes',
    was: (value: string) => `was ${value}`,
    why: 'Why',
    listenFor: 'Listen for',
    createRecipe: 'Create as new recipe',
    draftNote: (why: string, listenFor: string) => `Why: ${why}\nListen for: ${listenFor}`,
    duelRead: 'Coach’s read',
    duelReadLoading: 'The coach is reading the result…',
    readDuel: 'Ask the coach about this duel',
    nextTest: 'Next test',
    createThis: 'Create this recipe',
    brewRead: 'Coach',
    aboutRecipe: (code: string, name: string | null) => `About ${code}${name ? ` · ${name}` : ''}`,
    aboutBean: (name: string) => `About ${name}`,
    aboutClear: 'Ask about everything instead',
    aboutQuestionRecipe: (code: string) => `What would make ${code} win more duels?`,
    aboutQuestionBean: (name: string) => `How should we brew ${name}?`,
  },

  tips: {
    beanTitle: 'Coach tips for this coffee',
    recipeTitle: 'Coach review',
    loadingBean: 'The coach is reading this coffee. This can take up to a minute.',
    loadingRecipe: 'The coach is reading this recipe. This can take up to a minute.',
    getBean: 'Get coach tips',
    getRecipe: 'Get the coach’s review',
    getHint: 'One AI call from the monthly budget.',
    update: 'Update tips',
    updating: 'Updating…',
    written: (when: string) => `Written ${when}`,
    staleBean: 'The coffee was edited after these tips.',
    staleRecipe: 'The recipe was edited after this review.',
    notConfigured: 'Coach tips appear here once the owner adds the AI key.',
    offline: 'Coach tips need a connection.',
    needsKey: 'The coach explains this once the owner adds the AI key.',
    start: 'Starting recipe',
    checks: 'Check before duelling it',
    nextTest: 'Next test',
    askAbout: 'Ask the coach',
  },

  quickLog: {
    title: 'Quick log',
    open: 'Quick log',
    hint: 'Say or type the brew. The coach fills in the form; you check it before saving.',
    label: 'Your brew, in your words',
    placeholder: 'e.g. R3 on Guji, TDS 1.32, 245 grams, sweet but thin when cool',
    mic: 'Speak',
    listening: 'Listening… tap to stop',
    micUnavailable: 'Voice input isn’t available in this browser. Type it instead.',
    fill: 'Fill in the form',
    filling: 'Reading it…',
    filled: 'Filled in what the coach could read. Check each field, then save.',
    nothingFound: 'The coach couldn’t read any fields from that. Add numbers like TDS or grams.',
    otherRecipe: (code: string) => `That sounds like ${code}.`,
    switchRecipe: (code: string) => `Log it on ${code}`,
    pickRecipe: 'Which recipe was it?',
    continue: 'Continue to the log',
    offline: 'Quick log needs a connection. Use the form below.',
  },

  duel: {
    title: 'Duel',
    start: 'Start a duel',
    now: 'Now',
    results: 'Results',
    noResults: 'No duels yet. A duel ranks two recipes the way judges do: blind, one cup against the other.',
    leaderboard: 'Leaderboard',
    topRecipes: 'Top recipes',
    bestPerMember: 'Best recipe per member',
    noRanked: 'Recipes get on the board after their first duel.',
    judgeNow: 'Your turn to judge',
    waitingForCups: 'Waiting for cups',
    youPour: 'You’re pouring',
    inProgress: 'Duel running',
    votesIn: (n: number, of: number) => `${n} of ${of} votes in`,
    judgesLine: (names: string) => `Judges: ${names}`,
    beat: (winner: string, loser: string) => `${winner} beat ${loser}`,
    drew: (x: string, y: string) => `${x} and ${y} drew`,
    score: (a: number, b: number) => `${a}–${b}`,
    cancelled: 'Cancelled',
    on: (bean: string) => `On ${bean}`,
    // New duel
    newTitle: 'New duel',
    recipeA: 'Recipe A',
    recipeB: 'Recipe B',
    pickRecipe: 'Pick a recipe',
    bean: 'Bean',
    noBean: 'No bean',
    judges: 'Judges',
    judgesHint: 'Pick 1 to 3. You pour, so you can’t judge.',
    notes: 'Notes',
    notesPlaceholder: 'What is this duel testing?',
    notesHint: 'Judges see this only after the reveal.',
    submit: 'Start duel',
    submitting: 'Starting…',
    needTwoRecipes: 'You need two recipes for a duel. Add another in Recipes.',
    pickBoth: 'Pick both recipes.',
    sameRecipe: 'Pick two different recipes.',
    pickJudges: 'Pick at least one judge.',
    tooManyJudges: 'Pick up to three judges.',
    noJudges: 'Nobody else is on the team yet. The owner adds baristas in Settings › Members.',
    // Live duel
    helperOnly: 'Helper only',
    pourX: 'In cup X',
    pourY: 'In cup Y',
    markCups: 'Mark the cups underneath, not on the side.',
    cupsReady: 'Cups are ready',
    helperJudging: 'The judges are tasting. Votes stay hidden until the reveal.',
    waitingTitle: 'Waiting for cups',
    waitingBody: 'The helper is pouring. Look away while the cups are marked.',
    judgeTitle: 'Which cup is better?',
    judgeBody: 'Taste both, then point together with the other judges.',
    voteX: 'X',
    voteY: 'Y',
    voteTie: 'Can’t separate',
    voteLabel: { x: 'X', y: 'Y', tie: 'Can’t separate' } as Record<string, string>,
    youVoted: (choice: string) => `You voted: ${choice}`,
    waitingVotes: (n: number, of: number) => `Waiting for the other judges. ${n} of ${of} votes in.`,
    onlooker: 'A duel is running. The result shows here after the reveal.',
    revealNow: (n: number) => `Reveal with ${plural(n, 'vote', 'votes')}`,
    cancelDuel: 'Cancel duel',
    cancelAgain: 'Tap again to cancel the duel',
    wins: (code: string) => `${code} wins`,
    draw: 'Draw',
    votesLine: (x: number, y: number, ties: number) =>
      `X ${x} · Y ${y}${ties ? ` · ${plural(ties, 'couldn’t separate', 'couldn’t separate')}` : ''}`,
    cup: (letter: string) => `Cup ${letter}`,
    votes: 'Votes',
    rematch: 'Rematch with cups swapped',
    rematchHint: 'X and Y swap, so cup position can’t decide it.',
    rematchOf: 'Rematch, cups swapped',
    rematchStarted: 'A rematch has started.',
    openRematch: 'Open the rematch',
    cancelledBody: 'This duel was cancelled. It doesn’t count toward Elo.',
    backToDuels: 'Back to duels',
    offline: 'You’re offline. This screen updates when you’re back online.',
    judging: 'Judging',
    pouring: 'Pouring',
    // Kinds of duel
    kindLabel: 'What kind of duel?',
    kinds: { recipes: 'Recipe duel', baristas: 'Barista duel' } as Record<string, string>,
    kindHints: {
      recipes: 'Two recipes, one person pours both cups. It ranks the recipes.',
      baristas: 'Two baristas, each brewing their own recipe, judged blind. It ranks the baristas.',
    } as Record<string, string>,
    baristaA: 'Barista A',
    baristaB: 'Barista B',
    pickBarista: 'Pick a barista',
    theirRecipe: 'Their recipe',
    pickBaristas: 'Pick both baristas.',
    sameBarista: 'Pick two different baristas.',
    pickTheirRecipes: 'Pick each barista’s recipe.',
    sameRecipeOk: 'Both can brew the same recipe: then it’s all technique.',
    judgesHintBaristas: 'Pick 1 to 3. You host and the baristas brew, so none of you can judge.',
    needTwoBaristas: 'A barista duel needs two baristas and at least one judge. The owner adds people in Settings › Members.',
    // A live barista duel
    versus: (a: string, b: string) => `${a} vs ${b}`,
    hostOnly: 'Host only',
    cupOf: (name: string) => `${name}’s cup`,
    placeCups: 'Put each barista’s cup on its letter. Mark the cups underneath, not on the side.',
    competingTitle: 'You’re competing',
    competingBody: (recipe: string, rival: string) => `Brew ${recipe} and hand your cup to the host. You’re up against ${rival}.`,
    openTimer: 'Open the brew timer',
    youCompete: 'You’re competing',
    youHost: 'You’re hosting',
    // Judging with criteria
    scoreTitle: 'Score both cups',
    scoreBody: 'Taste each cup and score all six, from 1 to 10. Then point at the better cup together.',
    scoreCup: (letter: string) => `Cup ${letter}`,
    pickWinner: 'Which cup is better?',
    scoreFirst: 'Score all six for both cups to vote.',
    scoresFavour: (letter: string, a: string, b: string) => `Your scores favour ${letter}, ${a} to ${b}. You decide.`,
    scoresLevel: (total: string) => `Your scores are level, ${total} each. You decide.`,
    // The reveal
    personWins: (name: string) => `${name} wins`,
    withRecipe: (code: string) => `with ${code}`,
    scoresTitle: 'Judges’ scores',
    scoresHint: 'The average of the judges, from 1 to 10.',
    total: 'Total',
    judgeLine: (vote: string, x: string, y: string) => `${vote} · X ${x}, Y ${y}`,
    // Standings
    baristas: 'Baristas',
    noBaristaDuels: 'Baristas are ranked after their first barista duel.',
    baristaSub: (record: string, overall: string | null) => (overall ? `${record} · overall ${overall}` : record),
  },

  teamSettings: {
    title: 'Team settings',
    row: 'Team and championship',
    rowSub: 'Team name, championship, AI coach and budget',
    name: 'Team name',
    champName: 'Championship',
    champNamePlaceholder: 'e.g. Jordan AeroPress Championship',
    champDate: 'Championship date',
    champDateHint: 'The Board counts down to it.',
    compNotes: 'Competition coffee notes',
    compNotesPlaceholder: 'What the organizer has said about the coffee',
    budget: 'AI budget per month (USD)',
    budgetHint: (spent: string) => `Spent this month: ${spent}. The coach stops for everyone once this is reached.`,
    save: 'Save',
    saved: 'Team settings saved.',
    budgetInvalid: 'Enter the budget in dollars, like 10.',
    models: 'AI coach',
    modelsHint: 'Prices are per million tokens, input / output. The budget counts what OpenRouter actually charges.',
    coachModel: 'Coach model',
    coachModelHint: 'Plans, tips on coffees and recipes, comparisons, readiness, today’s duels, duel reads and questions.',
    autoTips: 'Automatic coach tips',
    autoTipsHint:
      'When someone adds a coffee or a recipe, the coach reviews it the first time it’s opened. Each review is one AI call from the budget. When this is off, anyone can still tap “Get coach tips”.',
    quickModel: 'Quick model',
    quickModelHint: 'Quick log and the short read after each brew.',
    modelOption: (label: string, input: string, output: string) => `${label} · $${input} / $${output}`,
    anthropicModels: 'The coach uses Claude Sonnet 5 and Haiku 4.5 through your Anthropic key. Add an OpenRouter key in Cloudflare to choose other models here.',
    noKeyModels: 'Add an OpenRouter API key in Cloudflare to choose the coach’s models here (the README says how).',
  },

  backup: {
    title: 'Download backup',
    sub: 'Everything in one JSON file: beans, recipes, brews, duels, reports',
    working: (part: string, rows: number) => `Collecting ${part}… ${rows} rows`,
    done: (name: string) => `Saved ${name}.`,
    offline: 'The backup needs a connection.',
  },

  settings: {
    title: 'Settings',
    unsyncedWarning: (n: number) =>
      `${plural(n, 'brew on this phone hasn’t', 'brews on this phone haven’t')} synced yet. ${n === 1 ? 'It stays' : 'They stay'} here and ${n === 1 ? 'syncs' : 'sync'} next time you sign in on this phone.`,
    you: 'You',
    theme: 'Theme',
    themeSystem: 'System',
    themeLight: 'Light',
    themeDark: 'Dark',
    team: 'Team',
    members: 'Members',
    membersCount: (n: number) => plural(n, 'active member', 'active members'),
    changeTeamPin: 'Change team PIN',
    changeTeamPinBody: 'Baristas who sign in with the team PIN use the new one from their next sign-in. Anyone signed in now stays signed in.',
    newTeamPin: 'New team PIN',
    saveTeamPin: 'Save team PIN',
    teamPinSaved: 'Team PIN changed.',
    importV1: 'Import v1 backup',
    importV1Sub: 'Bring in beans, recipes, brews and duels from the old app',
    signOut: 'Sign out',
    signingOut: 'Signing out…',
    signOutOffline: 'Signing out needs a connection. Try again once you’re online.',
  },

  members: {
    title: 'Members',
    addTitle: 'Add a barista',
    addName: 'Name',
    addNamePlaceholder: 'e.g. Lina Haddad',
    addSubmit: 'Add barista',
    nameRequired: 'Enter their name.',
    added: (name: string) => `${name} added. They sign in with the team PIN.`,
    active: 'Active',
    inactive: 'Deactivated',
    locked: 'Locked',
    signsInWith: {
      owner: 'Owner PIN',
      personal: 'Own PIN',
      team: 'Team PIN',
    },
    lockedFor: (minutes: number) => `Locked for ${plural(minutes, 'minute', 'minutes')}`,
    sheet: {
      signsInWith: 'Signs in with',
      resetPin: 'Reset PIN',
      resetPinBody: (name: string) =>
        `Give ${name} a personal PIN. They sign in with it instead of the team PIN, and they’re signed out on their other phones.`,
      changeOwnerPin: 'Change owner PIN',
      changeOwnerPinBody: 'You stay signed in here. Other phones signed in as you are signed out.',
      newPin: 'New PIN',
      savePersonalPin: 'Set personal PIN',
      saveOwnerPin: 'Save owner PIN',
      pinSaved: 'PIN saved.',
      useTeamPin: 'Use the team PIN again',
      useTeamPinBody: 'Removes their personal PIN.',
      usingTeamPin: 'They sign in with the team PIN again.',
      deactivate: 'Deactivate',
      deactivateNamed: (name: string) => `Deactivate ${name}`,
      deactivateBody: 'Signs them out everywhere and hides them from the sign-in list. Their brews and recipes stay.',
      reactivate: 'Reactivate',
      reactivateNamed: (name: string) => `Reactivate ${name}`,
      reactivateBody: 'Puts them back on the sign-in list.',
      deactivated: (name: string) => `${name} is deactivated.`,
      reactivated: (name: string) => `${name} is back on the team.`,
    },
  },

  beans: {
    title: 'Beans',
    add: 'Add bean',
    emptyTitle: 'No beans yet',
    emptyBody: 'Add the coffees you train with, and mark the competition coffee when you know it.',
    compTag: 'Comp',
    competition: 'Competition coffee',
    daysOff: (n: number) => (n === 0 ? 'Roasted today' : n < 0 ? 'Roast date is ahead' : `${plural(n, 'day', 'days')} off roast`),
    /** Caption under the big day count in the bean list. */
    daysOffLabel: (n: number) => (n < 0 ? 'days until roast' : n === 1 ? 'day off roast' : 'days off roast'),
    noRoastDate: 'No roast date',
    brews: (n: number) => plural(n, 'brew', 'brews'),
    form: {
      newTitle: 'New bean',
      editTitle: 'Edit bean',
      name: 'Name',
      namePlaceholder: 'e.g. Ethiopia Guji Hambela',
      nameRequired: 'Give the bean a name.',
      roaster: 'Roaster',
      origin: 'Origin',
      originPlaceholder: 'Country, region',
      variety: 'Variety',
      process: 'Process',
      roastLevel: 'Roast level',
      roastDate: 'Roast date',
      altitude: 'Altitude',
      altitudePlaceholder: 'e.g. 2100 m',
      densityNotes: 'Density notes',
      notes: 'Notes',
      notesPlaceholder: 'Tasting notes, how it brews…',
      competition: 'Competition coffee',
      competitionHint: 'The organizer’s coffee for the championship. Only one bean holds this; marking it here clears the others.',
      competitionOwnerOnly: 'Only the owner can change the competition coffee.',
      processOptions: ['Washed', 'Natural', 'Honey', 'Anaerobic', 'Carbonic maceration', 'Wet-hulled'],
      roastOptions: ['Light', 'Medium-light', 'Medium', 'Medium-dark', 'Dark'],
      create: 'Add bean',
      save: 'Save bean',
      added: (name: string) => `${name} added.`,
      details: 'Details',
    },
  },

  recipes: {
    title: 'Recipes',
    new: 'New recipe',
    newShort: 'New',
    mine: 'Mine',
    everyone: 'Everyone',
    scopeLabel: 'Whose recipes',
    allBeans: 'All beans',
    beanLabel: 'Bean',
    beanFilterNote: (bean: string) => `Elo from duels on ${bean} only.`,
    emptyTitle: 'No recipes yet',
    emptyBody: 'Create a recipe to start logging brews and running duels.',
    emptyOwnerBody: 'Create a recipe, or bring in your old data with Settings › Import v1 backup.',
    emptyMine: 'You haven’t created a recipe yet.',
    emptyBean: 'No recipes on this bean yet.',
    elo: 'Elo',
    record: (s: { wins: number; losses: number; draws: number }) => `${s.wins}–${s.losses}–${s.draws}`,
    recordLabel: 'W–L–D',
    noDuels: 'No duels yet',
    duels: (n: number) => plural(n, 'duel', 'duels'),
    rank: (n: number) => `#${n}`,
    compTag: 'Comp',
    untitled: 'Untitled',
    methods: { Inverted: 'Inverted', Standard: 'Standard' } as Record<string, string>,
    fields: {
      name: 'Name',
      bean: 'Bean',
      method: 'Method',
      filter: 'Filter',
      dose: 'Dose',
      water: 'Water',
      ratio: 'Ratio',
      temp: 'Temperature',
      grinder: 'Grinder',
      grind: 'Grind setting',
      waterRecipe: 'Water recipe',
      bloomWater: 'Bloom water',
      bloomEnds: 'Bloom ends at',
      agitation: 'Agitation',
      pressStarts: 'Press starts at',
      pressDuration: 'Press takes',
      bypass: 'Bypass',
      bypassTemp: 'Bypass temperature',
      otherSteps: 'Other steps',
      notes: 'Notes',
      elo: 'Elo',
      record: 'W–L–D',
      owner: 'Created by',
    },
    detail: {
      by: (name: string) => `by ${name}`,
      versionOf: (code: string) => `Version of ${code}`,
      cloneAndTweak: 'Clone and tweak',
      compare: 'Compare',
      lineage: 'Lineage',
      edit: 'Edit',
      lock: 'Lock as competition recipe',
      unlock: 'Unlock competition recipe',
      lockedTag: 'Competition recipe',
      lockedNote: 'Locked as the competition recipe. The owner has to unlock it before it can change.',
      lockedNoteOwner: 'Locked as the competition recipe. Unlock it to make changes.',
      notYours: (name: string) => `Only ${name} or the owner can edit this recipe. Clone it to make your own version.`,
      setup: 'Setup',
      averages: 'Brew averages',
      averagesFrom: (n: number) => `from ${plural(n, 'brew', 'brews')}`,
      noBrews: 'No brews logged for this recipe yet.',
      brews: 'Brews',
      latestOnly: 'Showing the latest 200 brews.',
      scores: {
        sweetness: 'Sweetness',
        acidity: 'Acidity',
        body: 'Body',
        clarity: 'Clarity',
        finish: 'Finish',
        overall: 'Overall',
        tds: 'TDS',
        ey: 'EY',
        time: 'Time',
      },
      overallShort: (v: string) => `Overall ${v}`,
      plannedTime: 'Planned time',
      whatChanged: (code: string) => `What changed from ${code}?`,
    },
    form: {
      newTitle: 'New recipe',
      cloneTitle: (code: string) => `Clone ${code}`,
      editTitle: (code: string) => `Edit ${code}`,
      cloneBanner: 'Change one or two things only, so the duel tells you what worked.',
      changes: (n: number, code: string) => (n === 0 ? `No changes from ${code} yet` : `${plural(n, 'change', 'changes')} from ${code}`),
      tooManyChanges: 'More than two changes: a duel won’t tell you which one mattered.',
      changed: 'Changed',
      sections: { recipe: 'Recipe', coffee: 'Coffee and water', steps: 'Steps', notes: 'Notes' },
      noBean: 'No bean',
      placeholders: {
        name: 'e.g. Cooler, finer',
        filter: 'e.g. Paper ×2',
        grinder: 'e.g. Comandante C40',
        grind: 'e.g. 24 clicks',
        waterRecipe: 'e.g. Third Wave light',
        agitation: 'e.g. 3 stirs N-S-E-W',
        bypassTemp: 'e.g. room temp',
        time: 'm:ss',
        otherSteps: 'Anything else, in order',
        notes: 'Why this version, and what to listen for',
      },
      timeHint: 'Minutes:seconds from the start, like 1:45.',
      durationHint: 'Seconds or m:ss.',
      timeInvalid: 'Use minutes:seconds, like 1:45.',
      numberInvalid: 'Enter a number, like 18 or 17.5.',
      ratio: (value: string) => `Ratio ${value}`,
      create: 'Save recipe',
      clone: 'Save new version',
      save: 'Save changes',
      history: (code: string, brews: number, duels: number) =>
        `${code} already has ${plural(brews, 'brew', 'brews')} and ${plural(duels, 'duel', 'duels')}. Changing its settings changes what those results mean. To test a change, clone it instead.`,
      cloneInstead: 'Clone instead',
      fixErrors: 'Fix the highlighted fields, then save again.',
    },
    compare: {
      title: 'Compare',
      pickTitle: (code: string) => `Compare ${code} with…`,
      pickAnother: 'Compare with another recipe',
      nothingToCompare: 'There’s no other recipe to compare with yet.',
      setting: 'Setting',
      differs: (n: number) => (n === 0 ? 'Same settings' : `${plural(n, 'setting differs', 'settings differ')}`),
      legend: 'Highlighted rows differ.',
      ours: 'Our recipes',
      champions: 'World champion recipes',
      /** Column tags, first then second, for each kind of pair. */
      roles: {
        versions: ['Old', 'New'],
        recipes: ['Older', 'Newer'],
        champion_ours: ['Champion', 'Ours'],
        champions: ['Earlier', 'Later'],
      } as Record<CompareFraming, [string, string]>,
      standing: 'Standing',
      plannedTime: 'Planned time',
      whatDiffers: 'What differs',
      allSettings: 'All settings',
      showAll: 'Show all settings',
      showDiffering: 'Show only what differs',
      coach: 'The coach explains',
      explain: 'Explain the differences',
      explainHint: 'In plain words, for each difference: why you’d do it, how it works, and what you’ll taste. One AI call, kept for the whole team.',
      explaining: 'The coach is comparing them. This can take up to a minute.',
      explainAgain: 'Explain again',
      stale: 'One of the recipes was edited after this.',
      why: 'Why',
      how: 'How it works',
      cup: 'In the cup',
      verdict: {
        versions: 'Is the new one better?',
        recipes: 'Which would win?',
        champion_ours: 'What we can borrow',
        champions: 'What they share',
      } as Record<CompareFraming, string>,
      next: 'Try next',
    },
    lineage: {
      title: 'Lineage',
      intro: 'Every version in this family, with its Elo. Tap one to open it.',
      current: 'You are here',
    },
  },

  champions: {
    title: 'Champion recipes',
    open: 'World champion recipes',
    intro:
      'Podium recipes from the World AeroPress Championship, as the champions published them. Add one to the team’s recipes to brew it on the timer and duel it against your own.',
    trust: 'Collected from the official championship pages and coffee press. Where sources disagree, the value is left empty and the recipe says why. Check the sources before relying on a number.',
    noFinal2020: 'No world final in 2020.',
    place: { 1: '1st', 2: '2nd', 3: '3rd' } as Record<number, string>,
    placeLong: (place: number, country: string) => `${['', '1st', '2nd', '3rd'][place] ?? place} place · ${country}`,
    yearTitle: (year: number) => `WAC ${year}`,
    winner: 'World champion',
    noRecipe: 'No recipe was published for this result.',
    add: 'Add to our recipes',
    addHint: 'Opens a new recipe with these settings. Pick your bean, check it, then save.',
    /** A champion recipe's short code in comparisons, e.g. "WAC 2019 · 1st". */
    code: (year: number, place: number) => `WAC ${year} · ${['', '1st', '2nd', '3rd'][place] ?? place}`,
    compareWith: 'Compare with our recipes',
    whyTitle: 'Why it works',
    explain: 'Explain this recipe',
    explainHint: 'In plain words: the idea behind it, why the champion likely chose each setting, and what we can take from it. One AI call, kept for the whole team.',
    explaining: 'The coach is reading this recipe. This can take up to a minute.',
    explainAgain: 'Explain again',
    why: 'Why',
    how: 'How it works',
    lessons: 'What we can take from it',
    steps: 'Steps as published',
    notes: 'About',
    caveats: 'What the sources leave open',
    sources: 'Sources',
    recipeName: (year: number, place: number, name: string) => `WAC ${year} ${['', '1st', '2nd', '3rd'][place] ?? place} · ${name}`,
    draftNote: (year: number, place: number, name: string, country: string, sources: string[]) =>
      `World AeroPress Championship ${year}, ${['', '1st', '2nd', '3rd'][place] ?? place} place: ${name} (${country}). As published; check before relying on a number.\nSources: ${sources.join(' ')}`,
    count: (n: number, from: number, to: number) => `${n} podium recipes, ${from}–${to}`,
  },

  brew: {
    title: 'Brew',
    pick: 'Pick a recipe to brew.',
    lastBrewed: 'Brewed last on this phone',
    inProgress: (code: string, time: string) => `Brewing ${code} · ${time}`,
    backToTimer: 'Back to the timer',
    planned: (time: string) => `Planned ${time}`,
    fits: 'fits in 5:00',
    over: (time: string) => `${time} over 5:00`,
    incomplete: 'This recipe has no press start or press time, so the timer can’t call the later steps. Add them to the recipe for the full guide.',
    editRecipe: 'Edit recipe',
    missingRecipe: 'That recipe isn’t on this phone yet. Go online once to load your recipes.',
    otherRunning: (code: string) => `A brew of ${code} is still going.`,
    goToOther: (code: string) => `Back to ${code}`,
    stopOther: 'Stop it and brew this',
    start: 'Start',
    pause: 'Pause',
    resume: 'Resume',
    startOver: 'Start over',
    logThis: 'Log this brew',
    logBrew: 'Log a brew',
    brewThis: 'Brew',
    setup: 'Setup',
    steps: 'Steps',
    ready: 'Ready',
    readyDetail: 'Tap Start as the water hits the coffee.',
    done: 'Done',
    doneDetail: 'Taste it, then log it.',
    over5: 'Over 5:00',
    left: (time: string) => `${time} left`,
    next: (title: string, at: string) => `Next: ${title} at ${at}`,
    paused: 'Paused',
    phases: {
      bloom: 'Bloom',
      steep: 'Pour and steep',
      flip: 'Flip',
      press: 'Press',
      bypass: 'Bypass',
      pour: 'Pour',
    } as Record<string, string>,
    phaseDetail: {
      bloom: (grams: string | null) => (grams ? `Pour ${grams} and let it bloom.` : 'Pour and let it bloom.'),
      steep: (water: string | null, agitation: string | null) =>
        [water ? `Pour to ${water}.` : 'Pour the rest.', agitation ? `${agitation}.` : '', 'Cap and steep.'].filter(Boolean).join(' '),
      flip: 'Flip it onto the cup.',
      press: (time: string) => `Press steadily for ${time}.`,
      bypass: (grams: string, temp: string | null) => `Add ${grams} of water${temp ? ` (${temp})` : ''}.`,
      pour: 'Pour into the judging cup.',
    },
    offlineNote: 'You’re offline. The timer works; brews you log wait on this phone and sync later.',
    waitingTitle: (n: number) => `${plural(n, 'brew is', 'brews are')} waiting to sync`,
    waitingBody: (n: number) =>
      n === 1 ? 'It goes up by itself when there’s a connection.' : 'They go up by themselves when there’s a connection.',
    syncNow: 'Sync now',
    refused: (label: string, reason: string) => `${label} couldn’t be saved: ${reason}`,
    discard: 'Discard',
    log: {
      title: 'Log brew',
      bean: 'Bean',
      noBean: 'No bean',
      grind: 'Grind used',
      totalTime: 'Total time',
      tds: 'TDS',
      beverage: 'Beverage weight',
      ey: (value: string) => `Extraction yield ${value}`,
      eyNeeds: 'Extraction yield shows once TDS and beverage weight are in (and the recipe has a dose).',
      scores: 'Scores',
      scoresHint: 'Drag to score from 1 to 10. Leave a score at — to skip it.',
      scoreLabels: {
        sweetness: 'Sweetness',
        acidity: 'Acidity',
        body: 'Body',
        clarity: 'Clarity',
        finish: 'Finish',
        overall: 'Overall',
      },
      unset: '—',
      clear: 'Clear',
      notes: 'Notes',
      notesPlaceholder: 'Hot, warm, cool?',
      outOfRange: (min: string, max: string) => `Enter a number from ${min} to ${max}.`,
      timeTooLong: (max: string) => `Enter a time up to ${max}.`,
      save: 'Save brew',
      saved: 'Brew saved.',
      queued: 'Brew saved on this phone.',
    },
  },

  importV1: {
    title: 'Import v1 backup',
    intro: 'Pick the JSON backup exported from the old AeroPress Lab. Everything comes in as yours, and anything already here is skipped, so importing twice is safe.',
    choose: 'Choose backup file',
    chooseAnother: 'Choose a different file',
    reading: 'Reading the file…',
    fileErrors: {
      not_json: 'That file isn’t a JSON backup. Export the backup again from the old app and pick that file.',
      not_v1: 'That file isn’t an AeroPress Lab backup. Pick the file the old app exported.',
      wrong_version: 'That backup comes from a different version of the app. This import reads v1 backups.',
    } as Record<string, string>,
    readyTitle: 'Ready to import',
    fileName: (name: string) => `From ${name}`,
    kinds: { beans: 'Beans', recipes: 'Recipes', brews: 'Brews', duels: 'Duels', settings: 'Championship details' } as Record<string, string>,
    settingsFound: 'Championship name, date and competition coffee notes',
    checkTitle: 'Worth knowing before you import',
    planWarnings: {
      missing_id: (n: number) => `${plural(n, 'record has', 'records have')} no id; each gets a fixed one so re-importing stays safe.`,
      duplicate_id: (n: number) => `${plural(n, 'record repeats', 'records repeat')} an id; only the first copy comes in.`,
      not_a_record: (n: number) => `${plural(n, 'entry isn’t', 'entries aren’t')} a record and will be skipped.`,
      unnamed_bean: (n: number) => `${plural(n, 'bean has', 'beans have')} no name and will be called “Unnamed bean”.`,
      bad_number: (n: number) => `${plural(n, 'number', 'numbers')} couldn’t be read and will be left empty.`,
      bad_time: (n: number) => `${plural(n, 'time', 'times')} couldn’t be read (expected m:ss) and will be left empty.`,
      bad_date: (n: number) => `${plural(n, 'date', 'dates')} couldn’t be read and will be left empty.`,
      score_out_of_range: (n: number) => `${plural(n, 'score is', 'scores are')} outside 1–10 and will be left empty.`,
      method_defaulted: (n: number) => `${plural(n, 'recipe has', 'recipes have')} no method we recognise, so ${n === 1 ? 'it’s' : 'they’re'} set to Inverted. Check after importing.`,
      lineage_loop: (n: number) => `${plural(n, 'lineage loops', 'lineages loop')} back on itself; the loop will be cut.`,
      parent_not_in_file: (n: number) => `${plural(n, 'recipe was', 'recipes were')} cloned from a recipe that isn’t in this file.`,
      bean_not_in_file: (n: number) => `${plural(n, 'record names', 'records name')} a bean that isn’t in this file.`,
      recipe_not_in_file: (n: number) => `${plural(n, 'record names', 'records name')} a recipe that isn’t in this file.`,
      'brews:recipe_not_in_file': (n: number) =>
        `${plural(n, 'brew names', 'brews name')} a recipe that isn’t in this file; ${n === 1 ? 'it comes' : 'they come'} in without a recipe.`,
      'duels:recipe_not_in_file': (n: number) =>
        `${plural(n, 'duel names', 'duels name')} a recipe that isn’t in this file; ${n === 1 ? 'it’s' : 'they’re'} left out of the ranking.`,
      'recipes:bean_not_in_file': (n: number) => `${plural(n, 'recipe names', 'recipes name')} a bean that isn’t in this file.`,
      'brews:bean_not_in_file': (n: number) => `${plural(n, 'brew names', 'brews name')} a bean that isn’t in this file.`,
      'duels:bean_not_in_file': (n: number) => `${plural(n, 'duel names', 'duels name')} a bean that isn’t in this file.`,
      duel_missing_recipe: (n: number) => `${plural(n, 'duel is', 'duels are')} missing a recipe and will be skipped.`,
      duel_bad_winner: (n: number) => `${plural(n, 'duel names', 'duels name')} a winner that wasn’t in the duel and will be skipped.`,
    } as Record<string, (n: number) => string>,
    ignoredTitle: 'Fields this app doesn’t use (left out)',
    ignoredField: (kind: string, field: string, n: number) => `${kind}.${field} (${n})`,
    start: 'Import everything',
    progress: (kind: string, done: number, total: number) => `Importing ${kind.toLowerCase()}… ${done} of ${total}`,
    doneTitle: 'Import finished',
    resultLine: (inserted: number, already: number, skipped: number) =>
      [
        `${inserted} added`,
        already ? `${already} already here` : '',
        skipped ? `${skipped} left out` : '',
      ]
        .filter(Boolean)
        .join(' · '),
    serverNotesTitle: 'What changed on the way in',
    serverWarnings: {
      'beans:extra_competition_coffee': (n: number, ex: string[]) =>
        `${plural(n, 'bean was', 'beans were')} also marked as the competition coffee (${ex.join(', ')}). Only one can be; the marker stayed where it was.`,
      'recipes:bean_missing': (n: number) => `${plural(n, 'recipe points', 'recipes point')} to a bean that isn’t in the backup, so ${n === 1 ? 'it has' : 'they have'} no bean now.`,
      'recipes:parent_missing': (n: number) => `${plural(n, 'recipe was', 'recipes were')} cloned from a recipe that isn’t in the backup, so ${n === 1 ? 'it starts' : 'they start'} a new lineage.`,
      'recipes:code_renamed': (n: number, ex: string[]) => `${plural(n, 'recipe code was', 'recipe codes were')} already in use and got the next free number (${ex.join(', ')}).`,
      'recipes:extra_lock': (n: number) => `${plural(n, 'more recipe was', 'more recipes were')} marked as the competition recipe. Only one can be locked, so ${n === 1 ? 'it was' : 'they were'} left unlocked.`,
      'brews:recipe_missing': (n: number) => `${plural(n, 'brew belongs', 'brews belong')} to a recipe that isn’t in the backup. ${n === 1 ? 'It was' : 'They were'} kept without a recipe.`,
      'brews:bean_missing': (n: number) => `${plural(n, 'brew names', 'brews name')} a bean that isn’t in the backup, so ${n === 1 ? 'it has' : 'they have'} no bean now.`,
      'duels:recipe_missing': (n: number) => `${plural(n, 'duel', 'duels')} involved a recipe that isn’t in the backup, so ${n === 1 ? 'it was' : 'they were'} left out of the ranking.`,
      'duels:bad_winner': (n: number) => `${plural(n, 'duel names', 'duels name')} a winner that wasn’t in the duel, so ${n === 1 ? 'it was' : 'they were'} left out.`,
      'duels:bean_missing': (n: number) => `${plural(n, 'duel names', 'duels name')} a bean that isn’t in the backup, so ${n === 1 ? 'it has' : 'they have'} no bean now.`,
    } as Record<string, (n: number, examples: string[]) => string>,
    failed: (message: string) =>
      `The import stopped: ${message} Everything before that is saved. Tap Import everything to carry on; records already imported are skipped.`,
    seeRecipes: 'See recipes',
    seeBeans: 'See beans',
  },

  errors: {
    offline: 'You’re offline. Check the connection and try again.',
    timeout: 'The connection is too slow right now. Try again in a moment.',
    generic: 'Something went wrong. Try again in a moment.',
    loadFailed: 'Couldn’t load the app. Check the connection and try again.',
    // Keyed by API error code. Functions receive the error body.
    byCode: {
      not_signed_in: 'You’re signed out. Sign in again to continue.',
      owner_only: 'Only the owner can do this.',
      wrong_pin: (e: { tries_left?: number }) =>
        e.tries_left === undefined
          ? 'Wrong PIN. Try again.'
          : `Wrong PIN. ${plural(e.tries_left, 'try', 'tries')} left before a 15-minute lock.`,
      locked: (e: { retry_after_ms?: number }) => {
        const minutes = Math.max(1, Math.ceil((e.retry_after_ms ?? 15 * 60_000) / 60_000));
        return `Too many wrong PINs. Try again in ${plural(minutes, 'minute', 'minutes')}.`;
      },
      member_not_found: 'That name is no longer on the team. Go back and pick your name again.',
      already_set_up: 'This team is already set up. Sign in instead.',
      name_taken: 'Someone on the team already has that name. Add a last initial to tell them apart.',
      pin_matches_team: 'The owner PIN must differ from the team PIN. Pick another PIN.',
      pin_matches_owner: 'The team PIN must differ from the owner PIN. Pick another PIN.',
      server_error: 'Something went wrong on our side. Try again in a moment. If it keeps happening, tell the owner.',
      database_updated: 'The app just set up its database. Try again.',
      database_not_ready:
        'The app couldn’t set up its database. Try again in a moment. If this keeps showing, the owner needs to run the deploy again (npm run deploy).',
      not_found: 'That no longer exists. Go back and refresh the list.',
      bean_not_found: 'That bean no longer exists. Pick another bean.',
      parent_not_found: 'The recipe you cloned no longer exists. Go back to the recipe list.',
      recipe_locked: 'This is the locked competition recipe. The owner has to unlock it before it can change.',
      recipe_not_found: 'That recipe no longer exists. Pick another recipe.',
      brew_id_taken: 'This brew clashes with another one. Log it again as a new brew.',
      wrong_member: 'Someone else logged this brew on this phone. It syncs when they sign in here again.',
      cups_not_ready: 'The cups aren’t ready yet. Wait for the helper to call them.',
      duel_over: 'This duel is already over. Start a new one or a rematch.',
      not_a_judge: 'Only the judges picked for this duel can vote.',
      already_voted: 'You’ve already voted in this duel. Votes can’t change.',
      not_duel_helper: 'Only the person who started this duel, or the owner, can do that.',
      helper_cannot_judge: 'You’re pouring, so you know which cup is which. Pick other judges.',
      barista_cannot_judge: 'A barista in this duel can’t judge it. Pick other judges.',
      barista_not_found: 'One of the baristas is no longer on the team. Pick them again.',
      judge_not_found: 'One of the judges is no longer on the team. Pick the judges again.',
      no_votes: 'No votes are in yet. Wait for at least one judge.',
      not_judging: 'The judges haven’t started yet. Call the cups ready first.',
      not_revealed: 'Only a revealed duel can be rematched.',
      no_judges_left: 'Nobody is left to judge a rematch. Start a new duel and pick judges.',
      ai_not_configured: 'The AI coach isn’t set up yet. The owner needs to add an OpenRouter or Anthropic API key in Cloudflare.',
      ai_key_invalid: 'The AI key was refused. The owner needs to check it in Cloudflare.',
      ai_busy: 'The AI coach is busy right now. Try again in a minute.',
      ai_billing: 'The AI account can’t take requests right now (out of credits, or billing). The owner needs to check it.',
      ai_failed: 'The AI coach couldn’t answer. Try again; if it keeps happening, tell the owner.',
      ai_bad_output: 'The coach’s answer came back unreadable twice. Try again in a moment.',
      ai_budget_exceeded: 'AI budget for this month is used up. The owner can raise it in Settings.',
      ai_refused: 'The coach couldn’t answer that one. Try asking another way.',
    } as Record<string, string | ((e: Record<string, unknown>) => string)>,
  },
};

export type Strings = typeof strings;
